meshtastic/Meshtastic-Android

app/src/main/java/com/geeksville/mesh/model/Channel.kt, app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
Allow to select a channel config different from default (Long Range)
#FirstRealModifs
=> Make Channel options available

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/menu/menu_main.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> Show app version in the app #5

app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/res/layout/adapter_node_layout.xml
it is using only the timestamp last position transmitted, not using the last received chat message
=> Display last time we receive a transmission from a node #65

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/res/layout/adapter_node_layout.xml
When the activity recreates while connected to the radio, the menu was not inflated, default Disconnect value was displayed
=> Fix bad connection status #84 

app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
The channel option display the current setting
=> Show network range setting when locked #138

app/src/main/java/com/geeksville/mesh/model/UIState.kt
I'm a total kotlin/android studio noob, but I think something like this would be helpful for when people just enter one word for their username.
=> Make 3 character short names from long name when long name is only one word

app/build.gradle, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt, app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt, app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/database/entity/Packet.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/DebugFragment.kt, app/src/main/java/com/geeksville/mesh/ui/PacketListAdapter.kt, app/src/main/res/drawable/cloud_download_outline_24.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/adapter_packet_layout.xml, app/src/main/res/layout/debug_fragment.xml, app/src/main/res/menu/menu_main.xml
A panel that display messages received in Meshservice
=> Added a debug panel

.idea/compiler.xml, .idea/gradle.xml, .idea/vcs.xml, app/build.gradle, app/src/debug/assets/firmware, app/src/main/assets/firmware, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/service/SoftwareUpdateService.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/release/assets/firmware, build.gradle, gradle/wrapper/gradle-wrapper.properties
(mostly so I can check CI to make sure my build works for others)
=> a collection of minor changes I'll eventually merge

app/src/main/AndroidManifest.xml, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/main/res/layout/settings_fragment.xml, app/src/main/res/values/strings.xml
* I exposed broadcast_position and ls_sleep properties in the UIState model
* When  broadcast_position == 0, I also do location_share = LocDisabled, which feels correct, but I maybe wrong. Let me know.
* Adds corresponding views to the resources and bind them to the model.
=> Added ability to edit broadcast_position and ls_sleep settings

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt, app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/main/res/layout/advanced_settings.xml, app/src/main/res/layout/settings_fragment.xml, app/src/main/res/menu/menu_main.xml, app/src/main/res/values/strings.xml
* Moved position_broadcast into a separate "advanced settings" screen
* Enforce minimum broadcast period on per-channel basis (to be about 1% of duty cycle of the channel)
=> Advanced settings

app/src/main/AndroidManifest.xml
Resolves https://github.com/meshtastic/Meshtastic-Android/issues/237
=> Do not use windowSoftInputMode=adjustPan

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/database/entity/Packet.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/LocationUtils.kt, app/src/main/res/menu/menu_main.xml, app/src/main/res/values/strings.xml
* Add menu option to store  (From, SNR, Time, Distance) from the last 500 messages in a CSV file. We only use POSITION_APP messages for that.
* Fixed location request interval for GPS-less devices - align that with positionBroadcastSec in radio preferences and ensure that when interval changes (usually when preferences are downloaded from radio), the location request is properly restarted.
=> Save messages in CSV file

app/src/main/res/values-sk/strings.xml
=> Slovak translation update

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/adapter_packet_layout.xml, app/src/main/res/layout/advanced_settings.xml, app/src/main/res/layout/debug_fragment.xml, app/src/main/res/layout/dropdown_menu_popup_item.xml, app/src/main/res/layout/settings_fragment.xml, app/src/main/res/menu/menu_main.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
- Added new variable "theme" to SharedPreferences
- **Function setUITheme**: check and set theme after app startup
- Added **new menu item**: Theme
- Added **new function chooseThemeDialog**: invoking dialog for choosing theme & settings SharedPreferences
- Added **new file for night theme color options**:  app/src/main/res/values-night/colors.xml
- Adjusting styles.xml to DayNight theme & toolbar styling
- Colors extracted to colors.xml 
- Added new strings
=> Added dark theme option

app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/drawable/ic_send_24.xml, app/src/main/res/layout/messages_fragment.xml
Missed having a "Send button" to send messages, so I made one.
Tried to keep it simple and follow current design aesthetic.
added:
- **sendButton** (ImageButton -> messages_fragment.xml + setOnClickListener -> MessagesFragment.kt)
- **multi-line text input** (removed android:singleLine="true" -> messages_fragment.xml)
- **200 character max text message limit** (android:maxLength="200" -> messages_fragment.xml) (real limit is 255 per packet, any way to calculate exact max text message size?)
Feedback is welcome!
=> Feature: Added Send button

.github/workflows/android.yml, app/src/main/AndroidManifest.xml, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/android/ContextServices.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/res/layout/channel_fragment.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml
Basic QR Code scanning feature using ZXing library IntentIntegrator.
Requires:
- android.permission.CAMERA
=> Feature: Camera QR Code scanning

.github/workflows/android.yml, .gitignore
- switch to JDK 11
- added CI upload for debug artifact
- added cert keys and mapbox token to .gitignore
=> CI build improvements

app/src/main/java/com/geeksville/mesh/model/Channel.kt, app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml
Add MediumFast & MediumSlow LoRa channels.
- ChannelOption.kt: vars SHORT, MEDIUM, LONG, VERY_LONG not changed (in case referenced)
- ChannelOption.kt: val minBroadcastPeriodSecs capped at >= 30 seconds
unsigned apk available from artifact here: https://github.com/meshtastic/Meshtastic-Android/actions/runs/1560891910
=> add LoRa channels (MediumFast, MediumSlow)

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt, app/src/main/res/layout/advanced_settings.xml
add is_always_powered setting to Android app > Advanced Settings
=> add is_always_powered

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
send and clear any queued messages in `offlineSentPackets` after a new connection is established
=> fix processing queued packets

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/main/res/values/strings.xml
- update Settings notifications to Snackbar
- make important notifications persistent & require user action (dismiss)
- update location_disabled & location_disabled_warning strings for clarity
=> improve Settings notifications

app/src/main/java/com/geeksville/mesh/MyNodeInfo.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/res/layout/adapter_node_layout.xml
add channelUtilization & airUtilTx to:
- MyNodeInfo
- UsersFragment
=> add channelUtilization & airUtilTx protos

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/model/MessagesState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/values/strings.xml
This PR is targeted at Issue: #201 
The current attempt in this PR is just to delete messages locally. 
Looking into "delete all messages" method & UI integration
Further discussions/enhancements can be made about having the option to delete messages from the entire mesh, similar to Signal's delete functionality (DELETE FOR ME, DELETE FOR EVERYONE).
=> !WIP Merge feature/delete-messages into Master

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt, app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt
Fixes  #340 and expands upon the written fields such that it (mostly) matches the range test plugin's exported file content.
Restructured this a bit to get more business logic out of the activity layer.  I moved it down to the viewmodel for now but this would really be moved into a repository.
=> Fixes #340 Improve CSV file export

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/res/values/styles.xml
=> add splash screen

app/src/main/java/com/geeksville/mesh/model/Channel.kt
https://github.com/meshtastic/Meshtastic-device/pull/1208
=> Change the default pre shared key to break backward compatibility of default channel

app/src/main/java/com/geeksville/mesh/model/UIState.kt
remove radioConfig isRouter reference
=> remove is_router

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
replace RadioConfig `locationSharing` enum with `locationShareDisabled` boolean
=> use locationShareDisabled boolean

app/src/main/res/layout/channel_fragment.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
correct pl translations, rename 'Scan' button to add translation
=> Correct pl transtations

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt, app/src/main/res/layout/advanced_settings.xml
remove RadioConfig is_always_powered from Advanced Settings
=> remove isAlwaysPowered

app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/model/NodeDB.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/service/MockInterface.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
move batteryLevel from Position to Telemetry
=> add telemetry.protos

app/src/main/java/com/geeksville/mesh/DataPacket.kt, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/MessagesState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/adapter_contact_layout.xml, app/src/main/res/layout/adapter_message_layout.xml, app/src/main/res/layout/fragment_contacts.xml, app/src/main/res/layout/messages_fragment.xml
add Contacts fragment & layout
- messages tab replaced with contacts tab
- contacts --> open messages list
- send and receive Direct Messages per contact
=> add Contacts

app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
updates for: https://github.com/meshtastic/Meshtastic-protobufs/pull/136
=> promote device metrics

app/src/main/java/com/geeksville/mesh/BaseActivity.kt, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/res/menu/menu_main.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ga/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko-rKR/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-no/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sq/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
Enhancement https://github.com/meshtastic/Meshtastic-Android/issues/13 add an option to force language X
=> add an option to force language X

app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/layout/messages_fragment.xml
=> use keyboard capitalization settings

app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/drawable/ic_retry_24.xml, app/src/main/res/drawable/ic_twotone_content_paste_go_24.xml, app/src/main/res/menu/menu_messages.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
Resend Button' on message selection
=>  meshtastic#73 'Resend Button' on message selection

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/MessagesState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- improve message delete logic
- clean up contacts & messages fragment and action mode callback
=> clean up contacts & messages fragments

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt, app/src/main/res/menu/menu_main.xml, app/src/main/res/values-pl/arrays.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
New menu position with selection map style.
=> #413 Add Satellite Map Layers

app/src/main/java/com/geeksville/mesh/model/MessagesState.kt, app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- long press nodes to send Direct Messages;
- removed logic to create empty contacts for all nodes;
- sort nodes by `lastHeard`.
=> improve users fragment

app/src/main/java/com/geeksville/mesh/android/ContextServices.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
improve Settings UI handling Bluetooth scan & connections:
- added visual feedback while scan callback is running;
- don't disable "add device" button;
- better handle CompanionDeviceManager results;
- clean up & fixes
=> bluetooth scan & connect UI rework

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothRepository.kt, app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt, app/src/main/java/com/geeksville/mesh/repository/radio/TCPInterface.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- Open device settings and discovery logic for other interfaces besides Bluetooth;
- Change BLE prerequisite and adapt requirements depending on interface choice.
=> expand interface options beyond Bluetooth

app/src/main/java/com/geeksville/mesh/repository/nsd/NsdRepository.kt, app/src/main/java/com/geeksville/mesh/repository/nsd/NsdRepositoryModule.kt, app/src/main/java/com/geeksville/mesh/repository/radio/TCPInterface.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- add `NSDManager` for mDNS/DNS-SD service discovery
- add TCP/IP interface connections
=> add network service discovery

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- add more modern QR code scanner library
- improve permission request & channel url processing
=> add ML Kit barcode scanner

app/src/main/java/com/geeksville/mesh/model/Channel.kt, app/src/main/java/com/geeksville/mesh/model/ChannelSet.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/test/java/com/geeksville/mesh/model/ChannelSetTest.kt
- add `LoraConfig` to `ChannelSet` since it is no longer part of the primary channel;
- add `LocalConfig` from `localonly.proto` to store combined Config oneofs.
=> localonly & apponly protobuf updates

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/android/ContextServices.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
improve permission logic & location enabled/disabled detection.
=> improve location checks

app/build.gradle, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/DataStoreModule.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/LocalConfigRepository.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/LocalConfigSerializer.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, build.gradle
store `LocalOnlyProto.LocalConfig` as [Proto DataStore](https://developer.android.com/topic/libraries/architecture/datastore).
=> create LocalConfig DataStore

app/src/main/java/com/geeksville/mesh/repository/usb/SerialConnectionImpl.kt
xref: #meshtastic/Meshtastic-device/pull/1517
=> Set default USB baud rate to 115200 to match Meshtastic-device

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt
handle new config coming from wantConfig
=> handle updated wantConfig

app/src/main/java/com/geeksville/mesh/MainActivity.kt
override back button to move task to background on root.
=> fix back not moving task to background

app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt
=> clear Bluetooth scan filter

app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- fix install source filter for ml kit code scanner
- fallback to zxing if that fails
=> fix code scanner choice by install source

app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/res/values/strings.xml
Show a warning when changing to a channel that will be using the default encryption key.
<details><summary>Screenshot</summary>
</details>
=> Show warning in dialog when using default encryption key

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt, app/src/main/res/layout/advanced_settings.xml, app/src/main/res/values/strings.xml
Add a button to factory reset the device in advanced settings.
I cannot actually confirm whether this works due to https://github.com/meshtastic/Meshtastic-device/issues/1597 but it does brick the device :joy:
=> Add factory reset button

app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/ChannelSetRepository.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/ChannelSetSerializer.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/DataStoreModule.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/LocalConfigRepository.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
store `AppOnlyProtos.ChannelSet`as [Proto DataStore](https://developer.android.com/topic/libraries/architecture/datastore).
=> create ChannelSet datastore

app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt
#478 - Waypoints 
This PR setups the MapFragment to display waypoints as an overlay.
=> Display waypoints on map

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
+ add gps time to position packet sent from phone
+ don't crash our app if we don't have myNodeNum
=> use gps time in position sent from phone

app/src/main/java/com/geeksville/mesh/android/ContextServices.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
use LocationManager for `hasGps()` and `gpsDisabled()`
=> use locationManager method for gps

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- detect admin channel and enable sending remote nodes admin messages (reboot/shutdown/etc...)
=> add remote node administration

app/src/main/AndroidManifest.xml, app/src/main/java/com/geeksville/mesh/model/ChannelSet.kt, app/src/test/java/com/geeksville/mesh/model/ChannelSetTest.kt
remove `www.` from link --> http://meshtastic.org/e/YXNkZnF3ZXJhc2RmcXdlcmFzZGZxd2Vy
=> update QR code convention

app/src/main/java/com/geeksville/mesh/repository/datastore/ChannelSetRepository.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
meshtastic/Meshtastic-device#1780
=> install channels from wantConfig

app/src/main/res/layout/adapter_node_layout.xml
fix battery icon, antenna icon and last heard not showing.
=> fix nodes card layout

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
fix #516: only update Nodeinfo with valid Telemetry oneOf
=> fix #516: check Telemetry oneOf to update Nodeinfo

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/res/menu/menu_nodes.xml, app/src/main/res/values/strings.xml
- local node: send a position packet message to remote node with `wantResponse=true`;
- remote node: reply with a position packet in response if it has a valid position.
closes #251 #508
=> feat: add option to request remote nodes position 

app/src/main/java/com/geeksville/mesh/model/NodeDB.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt, app/src/main/java/com/geeksville/mesh/ui/PreferenceItemList.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/BitwisePreference.kt, app/src/main/java/com/geeksville/mesh/ui/components/DropDownPreference.kt, app/src/main/java/com/geeksville/mesh/ui/components/EditTextPreference.kt, app/src/main/java/com/geeksville/mesh/ui/components/RegularPreference.kt, app/src/main/res/values/strings.xml
- add bitwise dropdown pref for position flags
- improve methods and reduce boilerplate
- improve TextField empty string validation and show error state
=> config clean up and updates

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/service/MeshServiceBroadcasts.kt
- force connection broadcast on `setDeviceAddress` false
- revert `broadcastMessageStatus`
- add AIDL `getConfig` / `beginEditSettings` / `commitEditSettings`
=> updates for atak forwarder 2.0

app/src/main/java/com/geeksville/mesh/NodeInfo.kt
Fixes issue reported here:
https://meshtastic.discourse.group/t/eviromental-sensor-wont-report-temperatures-below-0-c/6871/3
=> Account for negative metric values in telemetry

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- add `ENROUTE` and `QUEUED` status broadcast.
=> fix broadcastMessageStatus

app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt, app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothRepository.kt
- list paired devices from Android Bluetooth settings in app Settings tab.
=> list devices from adapter.bondedDevices

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl
re-submitting PR after sorting out username issues.
=> improve documentation for usage of bound service

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- update service `startForeground()` method
fixes #504
=> update foreground service start

app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt, app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/drawable/ic_twotone_how_to_reg_24.xml
- distinguish between implicit (top) and real ACKs (bottom) for DMs.
closes #549
=> feat: distinguish between implicit and real ACKs

app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt
refactor zoom level in `zoomToNodes()` to fit all nodes on the screen (because `zoomToBoundingBox()` doesn't work).
closes #509
=> refactor: calculate zoomToNodes zoom level

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
add client-side packet transmit queue (https://github.com/meshtastic/firmware/pull/1820)
=> feat: add packet transmit queue

app/src/main/res/values-uk/strings.xml
updated Ukrainian localization strings by @Krezalis
=> feat: update Ukrainian localization strings

app/src/main/res/values-hu/strings.xml
updated Hungarian localization strings by @sirgeoff
=> feat: update Hungarian localization strings

app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/service/MeshServiceBroadcasts.kt
make sure we broadcast all `MessageStatus` updates coming from the radio
=> fix: always broadcast MessageStatus updates

app/build.gradle, app/src/fdroid/java/com/geeksville/mesh/android/GeeksvilleApplication.kt, app/src/google/java/com/geeksville/mesh/android/GeeksvilleApplication.kt, app/src/main/java/com/geeksville/mesh/MainActivity.kt
Continued work on #6: move AppRating into google flavor only (contains `com.google.android.play:core-ktx`)
=> refactor: move askToRate() to GeeksvilleApplication

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/DataPacket.kt, app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt, app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt, app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/layout/dialog_add_waypoint.xml, app/src/main/res/values/strings.xml
Continued work on #478: https://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.Waypoint
- long press on map to open waypoint dialog and drop marker
- long press marker to open delete dialog
=> feat: Waypoints

app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt, app/src/main/res/values/strings.xml
Continued work on #478: edit waypoints
- long press marker to open edit dialog
- delete menu options: delete for me; delete for everyone.
=> feat: edit waypoints

app/src/main/res/values-pl/strings.xml
updated Polish localization strings by @wkawecki
=> feat: update Polish localization strings

app/src/main/res/values-de/strings.xml
updated German localization strings by _lonelywolf_ and _elrir_
=> feat: update German localization strings

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
=> use MeshPacketQueue

app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
adds a unique color to each node in the nodes list, with a color based on each nodes's `num` value.
=> feat: add node colors

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/database/entity/MeshLog.kt, app/src/main/java/com/geeksville/mesh/model/NodeDB.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/res/menu/menu_nodes.xml, app/src/main/res/values/strings.xml
Adds `traceroute` option to nodes list
- ref. https://github.com/meshtastic/firmware/pull/2026
closes #546
=> feat: add traceroute

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/CannedMessageConfigItemList.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/ExternalNotificationConfigItemList.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/PositionConfigItemList.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/UserConfigItemList.kt, app/src/main/res/menu/menu_nodes.xml, app/src/main/res/values/strings.xml
add remote node configuration
also closes #556
=> feat: add remote node configuration

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/ChannelSetRepository.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/ChannelSettingsItemList.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/EditChannelDialog.kt
adds options to add/edit/delete channels.
closes #544
closes #603
=> feat: add channel editor

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/EditDeviceProfileDialog.kt
adds option to import/export `DeviceProfile` configs from/to an external file
=> feat: add configs import/export

app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/EditDeviceProfileDialog.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/PacketResponseStateDialog.kt
introduce `PacketResponseState` and implement `PacketResponseState.Loading`
- add progress indicator and cancel button while loading configs
=> feat: add progress indicator and cancel button while loading configs

app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/PacketResponseStateDialog.kt
implement `PacketResponseState.Error`
- show dialog with error message when loading config fails
=> feat: add error handling when loading configs

app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/PacketResponseStateDialog.kt
implement `PacketResponseState.Success`
- add admin requests success confirmation
=> feat: add admin packet success confirmation

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/ChannelSetRepository.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/LocalConfigRepository.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/ModuleConfigRepository.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt
combine config data stores into `RadioConfigRepository`
=> refactor: combine config data stores into single repository source

app/src/main/java/com/geeksville/mesh/DataPacket.kt, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt, app/src/main/java/com/geeksville/mesh/repository/usb/UsbBroadcastReceiver.kt, app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/main/java/com/geeksville/mesh/util/CompatExtensions.kt
updates deprecated methods, classes, and flags introduced in Android SDK 33, while ensuring compatibility with previous Android versions
=> refactor: implement CompatExtensions

app/build.gradle, app/src/main/res/values-bg/strings.xml, app/src/main/res/xml/locales_config.xml
Hi, I have added Bulgarian translation to the app.
=> feat: add Bulgarian language

app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt, app/src/test/java/com/geeksville/mesh/NodeInfoTest.kt
=> Add option for Miles and Feet for distance

app/src/main/java/com/geeksville/mesh/repository/radio/TCPInterface.kt
fixes TCP Socket not closing properly when `onDeviceDisconnect` is called from service
=> fix: close Socket from onDeviceDisconnect

app/src/fdroid/java/com/geeksville/mesh/repository/location/SharedLocationManager.kt
adds `LocationManager` provider options (used in the F-Droid release):
- allows multiple provider listeners
- preferred `FUSED_PROVIDER` for Android 12+
=> feat: add preferred `LocationManager` providers

app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt, app/src/main/java/com/geeksville/mesh/util/EnableWakeLock.kt
enables Wake Lock to keep the map screen on
=> feat: add Wake Lock to map screen

app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
=> Honor radio's option to use Fahrenheit.

app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/main/res/layout/settings_fragment.xml, app/src/main/res/values/strings.xml
=> Adds Field to Specify Device IP

app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt, app/src/main/java/com/geeksville/mesh/repository/nsd/NsdRepository.kt, app/src/main/java/com/geeksville/mesh/repository/nsd/NsdRepositoryModule.kt, app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt, app/src/main/java/com/geeksville/mesh/repository/radio/TCPInterface.kt
- add `ConnectivityManager` network availability monitoring
- use 1 minute interval telemetry packets as heartbeat
=> feat: add network availability monitoring

app/src/main/java/com/geeksville/mesh/repository/radio/TCPInterface.kt
Implement basic TCP interface reconnection attempts:
- Use an [exponential backoff strategy](https://en.wikipedia.org/wiki/Exponential_backoff): wait for increasingly longer intervals between reconnection attempts. Initial backoff delay (`MIN_BACKOFF_MILLIS`) is _1 second_, and doubles on each failure (_2^n_) to a max (`MAX_BACKOFF_MILLIS`) of _5 minutes_. No jitter is needed (for collision avoidance);
- Maximum reconnection attempts: a maximum number of times to try can be specified (`MAX_RETRIES_ALLOWED`), for now defaults to Int.MAX_VALUE.
closes #649
=> feat: implement TCP interface reconnections

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/res/menu/menu_nodes.xml, app/src/main/res/values/strings.xml
- adds menu item to add/remove nodes from `LoRaConfig`.`ignoreIncomingList`
=> feat: add menu item to add/remove nodes from `ignoreIncomingList`

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/geeksville/mesh/MainActivity.kt, app/src/main/java/com/geeksville/mesh/android/ContextServices.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt, app/src/main/res/values/strings.xml, gradle.properties
Migrate from Android 12 (API level 31) to Android 13 (API level 33)
- [Notification runtime permission](https://developer.android.com/develop/ui/views/notifications/notification-permission)
- implement `shouldShowRequestPermissionRationale`
=> chore: update compileSdk and targetSdk to API 33

app/build.gradle, build.gradle
References
https://developer.android.com/studio/build/migrate-to-ksp
https://android-developers.googleblog.com/2021/09/accelerated-kotlin-build-times-with.html
https://github.com/google/dagger/releases/tag/dagger-2.48
https://dagger.dev/dev-guide/ksp
=> refactor: migrate from kapt to ksp

app/src/main/res/values-fr/strings.xml
updated French localization strings by _SavageBeast_
=> feat: update French localization strings

app/src/main/AndroidManifest.xml, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- Allow screen rotation to landscape mode
- Don't scale the qr code, or it will only be partially visible in landscape mode
=> Add a tablet friendly mode

app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt
In relation to : meshtastic/firmware#3053 , meshtastic/protobufs#418
The addition of Malaysia frequencies.
=> Add Malaysia Frequency

app/src/fdroid/java/com/geeksville/mesh/android/GeeksvilleApplication.kt, app/src/google/java/com/geeksville/mesh/android/GeeksvilleApplication.kt, app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
Just some small changes and simplifications in preparation for moving the settings fragment to Compose. I'll probably be doing it in chunks, so that the PRs aren't so huge
=> Refactor and cleanup

app/src/main/java/com/geeksville/mesh/ui/components/config/EditChannelDialog.kt
adds new ChannelSettings `position_precision` config
=> feat: add ChannelSettings `position_precision` config

app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
Scroll to bottom of messages list when:
- a message is sent
- first load: _findLastVisibleItemPosition() <= 0_
- bottom is visible: _findLastVisibleItemPosition() == itemCount - 1_
=> feat: add condition check to scroll to bottom of messages list

app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/5.json, app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt
First steps in fulfilling #826 
The app currently doesn't hang on to the number of satellites info that is on the position message. This adds that field to the DB so we can later display it in the node info
=> Add number of GPS satellites in view to DB for later display

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/NodeFilterTextField.kt, app/src/main/java/com/geeksville/mesh/ui/theme/Theme.kt, app/src/main/res/layout/nodelist_fragment.xml, app/src/main/res/values/strings.xml
Adds a text field to the node list that filters against node short name and long name. Filter updates with each character
Fulfills #683
=> Feature: Filter node list

app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
Previously, long pressing a node in the map would jump to a DM with that node. Now, it will jump to that node in the node list.
Fulfills #909
=> Long press node in map jumps to node in node list

app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/7.json, app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt, app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt, app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/database/entity/Packet.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt, app/src/main/res/drawable/ic_twotone_volume_off_24.xml, app/src/main/res/drawable/ic_twotone_volume_up_24.xml, app/src/main/res/layout/adapter_contact_layout.xml, app/src/main/res/menu/menu_messages.xml, app/src/main/res/values/strings.xml
closes #511
https://github.com/meshtastic/Meshtastic-Android/assets/48680741/167e624f-3f21-4844-afe6-2cfa316eba6f
=> feat: add `ActionMenu` option to mute contacts

build.gradle
Reverts meshtastic/Meshtastic-Android#1024
=> Revert "chore(deps): update com.google.firebase:firebase-crashlytics-gradle to v3"

app/src/androidTest/java/com/geeksville/mesh/NodeInfoDaoTest.kt, app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt, app/src/main/java/com/geeksville/mesh/model/NodeDB.kt, app/src/main/java/com/geeksville/mesh/model/SortOption.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt, app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/ui/NodeSortButton.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/NodeFilterTextField.kt, app/src/main/java/com/geeksville/mesh/ui/map/CacheLayout.kt, app/src/main/java/com/geeksville/mesh/ui/map/DownloadButton.kt, app/src/main/java/com/geeksville/mesh/ui/map/EditWaypointDialog.kt, app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt, app/src/main/java/com/geeksville/mesh/ui/map/MapViewWithLifecycle.kt, app/src/main/res/drawable/ic_twotone_sort_24.xml, app/src/main/res/values/strings.xml
- adds nodelist sort options;
- moves nodelist filter into database query;
- adds option to include unknown names.
=> feat: add nodelist sort options

app/build.gradle, app/src/main/java/com/geeksville/mesh/repository/location/LocationRepository.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- Added `androidx.core:core-location-altitude:1.0.0-alpha02`;
- Implemented `AltitudeConverterCompat.addMslAltitudeToLocation(context, location)` to convert `altitude` (above the WGS84 reference ellipsoid) to Mean Sea Level (MSL) and add MSL altitude and accuracy to the location object.
Reference:
- https://issuetracker.google.com/issues/195660815
- Brian Julian and Michael Angermann. "Resource efficient and accurate altitude conversion to Mean Sea Level." [2023 IEEE/ION Position, Location and Navigation Symposium (PLANS)](https://www.ion.org/plans/abstracts.cfm?paperID=12011).
=> feat: implement MSL altitude using `AltitudeConverterCompat`

app/build.gradle, app/detekt-baseline.xml, config/detekt/detekt.yml
Adds [detekt](https://detekt.dev/) gradle plugin to do code smell analysis and prevent smelly code.
Includes default generated config file. Also includes baseline file that ignores already smelly code to focus on ensuring no new smells get added.
=> feat: adds detekt gradle plugin

app/src/main/java/com/geeksville/mesh/repository/network/MQTTRepository.kt
reference: https://github.com/meshtastic/firmware/pull/4305
=> refactor: remove ClientProxy MQTT `status` topic

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
=> fix: queued messages not being sent once reconnected

app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/AdaptiveTwoPane.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/ChannelSettingsItemList.kt, config/detekt/detekt.yml
=> feat: add adaptive two-pane layout to `ChannelScreen`

app/src/androidTest/java/com/geeksville/mesh/compose/ScannedQrCodeDialogTest.kt, app/src/main/java/com/geeksville/mesh/ui/components/ScannedQrCodeDialog.kt
adds Compose UI testing for `ScannedQrCodeDialog`
=> test: add `ScannedQrCodeDialogTest`

app/src/androidTest/java/com/geeksville/mesh/compose/ScannedQrCodeDialogTest.kt, app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/ScannedQrCodeDialog.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/ChannelSettingsItemList.kt, app/src/main/res/values/strings.xml
=> refactor: `QrCodeScanDialog` with single channel list and Add/Remove toggle

app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt, app/src/main/java/com/geeksville/mesh/ui/MetricsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/SignalInfo.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/CustomCharts.kt, app/src/main/res/menu/menu_nodes.xml, app/src/main/res/values/strings.xml
- The Row with the Ch and Air Util would break into 2 lines due to long strings.
- Anything DeviceDetails to Metrics
=> Refactor NodeDetails to Metrics

app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/res/values/strings.xml
=> fix(conifg): implement `sessionPasskey` handling for admin requests

app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/13.json, app/src/androidTest/java/com/geeksville/mesh/NodeInfoDaoTest.kt, app/src/androidTest/java/com/geeksville/mesh/PacketDaoTest.kt, app/src/main/java/com/geeksville/mesh/MyNodeInfo.kt, app/src/main/java/com/geeksville/mesh/NodeInfo.kt, app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt, app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt, app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt, app/src/main/java/com/geeksville/mesh/database/entity/MyNodeEntity.kt, app/src/main/java/com/geeksville/mesh/model/NodeDB.kt, app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Continued work on #1250
- replaces `MyNodeInfo` with `MyNodeEntity`
- removes `NodeInfo` and `MyNodeInfo` from Room database
=> refactor: replace `MyNodeInfo` with `MyNodeEntity`

app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt, app/src/main/java/com/geeksville/mesh/model/map/clustering/MarkerClusterer.java, app/src/main/java/com/geeksville/mesh/model/map/clustering/RadiusMarkerClusterer.java, app/src/main/java/com/geeksville/mesh/model/map/clustering/StaticCluster.java, app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
Implements M Kergall's [osmbonuspack](https://github.com/MKergall/osmbonuspack) Marker Clustering feature.
I was not able to implement the library as a dependency, as I could not customize the markers to match the markers currently used. I put the relevant parts of the library in with modifications to the markers.
=> Implement marker clustering

app/src/main/java/com/geeksville/mesh/util/LocationUtils.kt
Small pi improvement pointed out by users on Discord.
[Pi](https://en.wikipedia.org/wiki/Pi) is approximately equal to 3.14159
=> Small improvement to the pi approximation.

app/src/main/java/com/geeksville/mesh/ui/components/EditBase64Preference.kt, app/src/main/java/com/geeksville/mesh/ui/components/EditListPreference.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/SecurityConfigItemList.kt
adds option for 3 admin keys in `SecurityConfig`
closes #1293
=> feat: add option for 3 admin keys in `SecurityConfig`

app/src/androidTest/java/com/geeksville/mesh/compose/EditDeviceProfileDialogTest.kt, app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt, app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt, app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/EditDeviceProfileDialog.kt
adds option to include `fixed_position` using `DeviceProfile`  import/export.
reference: https://github.com/meshtastic/protobufs/pull/576
=> feat: add `fixed_position` to config import/export

app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
This adds the `Telemetry.LocalStats` to the service notification. This information includes the number of online and total nodes, as well as other local stats. It also updates the notification summary and adds local stats telemetry handling.
This implementation should also automatically display new fields in the proto as they are added.
resolves #1290
=> feat: Add local device stats to the service notification

app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt, app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt
Prepares for Compose navigation using NavHost for all screens.
=> refactor(config): extract screen logic from `NavHost`

app/src/main/java/com/geeksville/mesh/database/MeshLogRepository.kt, app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt, app/src/main/java/com/geeksville/mesh/ui/NavGraph.kt, app/src/main/java/com/geeksville/mesh/ui/NodeDetailsScreen.kt, app/src/main/java/com/geeksville/mesh/ui/components/TracerouteLog.kt, app/src/main/res/values/strings.xml
Adds traceroute logs to node detail screen
=> feat: traceroute log

app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt, app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt, app/src/main/java/com/geeksville/mesh/ui/NavGraph.kt, app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt, app/src/main/java/com/geeksville/mesh/ui/RadioConfigScreen.kt
- migrate Compose navigation to type-safe args
- pass nav args to ViewModel using SavedStateHandle
=> refactor: migrate Compose navigation to type-safe args

app/src/main/java/com/geeksville/mesh/ui/SignalInfo.kt, app/src/main/java/com/geeksville/mesh/ui/components/LoraSignalIndicator.kt, app/src/main/java/com/geeksville/mesh/ui/components/SignalMetrics.kt
Visual improvement to the NodeItem's signal data.
=> Signal Quality in NodeItem

app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/15.json, app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt, app/src/main/java/com/geeksville/mesh/database/entity/NodeEntity.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/java/com/geeksville/mesh/ui/NodeItem.kt, app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/NodeMenu.kt
- https://github.com/meshtastic/firmware/pull/5319
=> refactor: move ignore node to `is_ignored` field in `NodeInfo`

app/src/main/java/com/geeksville/mesh/model/Message.kt, app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt, app/src/main/java/com/geeksville/mesh/ui/NavGraph.kt, app/src/main/java/com/geeksville/mesh/ui/components/config/PacketResponseStateDialog.kt, app/src/main/java/com/geeksville/mesh/util/UiText.kt
introduces `UiText` class to defer string resolution to the UI layer
=> refactor: remove `getString()` from `RadioConfigViewModel`

app/src/main/java/com/geeksville/mesh/ui/components/CommonCharts.kt, app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt, app/src/main/java/com/geeksville/mesh/ui/components/PowerMetrics.kt
Using the same blue color in both the power and environment metrics. This blue variation works better with dark themes.
=> Graphs Blue Color

gradle/libs.versions.toml
=> fix: add crashlytics version reference

app/src/main/java/com/geeksville/mesh/ui/components/CommonCharts.kt, app/src/main/java/com/geeksville/mesh/ui/components/DeviceMetrics.kt, app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt, app/src/main/java/com/geeksville/mesh/util/GraphUtil.kt
- refactor: removed unused constants and function
=> feat: Updated the env metrics graph to use the latest graph features

app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/NetworkConfigItemList.kt, app/src/main/res/values/strings.xml
Adds a toggle to enable or disable mesh via UDP.
Resolves #1688 
| <img src="https://github.com/user-attachments/assets/5c40d9af-171b-403f-b06c-0523c5ee7a9f" width="300"/> | <img src="https://github.com/user-attachments/assets/98215c45-6876-462d-a627-68e256ce01e1" width="300"/> |
=> feat #1688: Add UDP mesh toggle

app/src/main/java/com/geeksville/mesh/ui/components/CommonCharts.kt, app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt, app/src/main/java/com/geeksville/mesh/ui/components/PowerMetrics.kt, app/src/main/java/com/geeksville/mesh/ui/theme/Color.kt, app/src/main/res/values/strings.xml
- Plotting the barometric pressure on the environment metrics graph.
- Only plotting the IAQ or barometric pressure when we have actual data for them.
=> Graph Barometric Pressure

README.md
analytics from https://repobeats.axiom.co/
=> feat: Update README.md to add repository statistics

app/src/main/java/com/geeksville/mesh/DataPacket.kt, app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Let the user specify the wantAck functionality.
=> Expose wantAck in Mesh Packet

app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/java/com/geeksville/mesh/ui/components/NodeFilterTextField.kt, app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt, app/src/main/res/values/strings.xml
Resolves issue #1632 
Created, or updated content descriptions for talkback.
=> Accessibility #1632

renovate.json
grouping was not behaving, backing off
=> chore(renovate): revert grouping

app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/NetworkConfigItemList.kt
Fixes display of UDP toggle - reported by @b8b8
=> fix: display udp toggle when hasWifi OR hasEthernet

.github/release.yml
Adds a release template config for formatting the autogenerated release notes.
=> chore(repo): Add release template

app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/SecurityConfigItemList.kt
=> fix: disable editing of Public Key field

app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
#1495 
Users reported blank graphs when a NaN value was present for a temperature reading.
=> Fix: NaN Blank Environment Graph

app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/SecurityConfigItemList.kt
=> Fix: actually copy public key

app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt, app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt, app/src/main/java/com/geeksville/mesh/ui/components/IndoorAirQuality.kt, app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/StoreForwardConfigItemList.kt, app/src/main/res/values/strings.xml
Extracts some more hardcoded strings to make them available for translation.
=> refactor: extract hardcoded NodeDetail strings

renovate.json
adds submodule update functionality to Renovate
=> chore(submodules): Enable submodule support in renovate config

app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfig.kt, app/src/main/res/values/strings.xml
extract RadioConfig strings for Import/Export Config
=> chore: extract string resources for import and export config

app/build.gradle
replace derecated dsl function
=> fix(gradle): resourceConfigurations replaces resconfigs

.github/workflows/stale.yml
adds an action to prune old Issues and PRs
=> chore(repo): stale.yml

app/src/main/java/com/geeksville/mesh/ui/Main.kt, app/src/main/java/com/geeksville/mesh/ui/Settings.kt, app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt, app/src/main/java/com/geeksville/mesh/ui/theme/Theme.kt
- adressed theme issues with system bars
- updated messages to use secondary and tertiary theme colors, fixes #1869  
- Some rework on Settings/Connections screen ui and logic for Connection selection, Analytics and BugTracking controls.
-
=> fix: M3 bug squashing

app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt, app/src/main/java/com/geeksville/mesh/model/Node.kt, app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/ContactItem.kt, app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt, app/src/main/java/com/geeksville/mesh/ui/NodeItem.kt, app/src/main/java/com/geeksville/mesh/ui/NodeScreen.kt, app/src/main/java/com/geeksville/mesh/ui/Share.kt, app/src/main/java/com/geeksville/mesh/ui/components/NodeFilterTextField.kt, app/src/main/java/com/geeksville/mesh/ui/components/NodeMenu.kt, app/src/main/java/com/geeksville/mesh/ui/preview/NodePreviewParameterProvider.kt, app/src/main/res/values/strings.xml
Functionality to support the `user.isUnmessageable` field from the protos
=> feat: Unmessageable

app/src/main/java/com/geeksville/mesh/service/MeshService.kt
This change ensures that `handleReceivedUser` is consistently invoked when a new contact is added to the device. This maintains data integrity and ensures user information is correctly updated in the on phone nodeDb and ui.
=> fix: Ensure handleReceivedUser is called when adding contacts

.github/workflows/codeql.yml
this isn't providing a ton of value by running it constantly.. moving it to weekly and removing the required check if there is one
=> chore(codeql): run only weekly

app/src/main/java/com/geeksville/mesh/ui/Main.kt, app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
Adds 30s cooldown to the action button for traceroute.
https://github.com/user-attachments/assets/812180b6-b957-4d46-b7fc-426b6df64806
=> feat: add cooldown to Traceroute action button

app/src/main/java/com/geeksville/mesh/ui/map/MapView.kt, app/src/main/java/com/geeksville/mesh/ui/map/components/EditWaypointDialog.kt, app/src/main/res/values/strings.xml
=> Added waypoint expiration picker

app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt
=> fix: update start destination to NodesGraph when connected

app/src/main/java/com/geeksville/mesh/navigation/MapRoutes.kt, app/src/main/java/com/geeksville/mesh/ui/Main.kt
The additional map graph was causing the state not to be saved, and nav logic was causing backstack weirdness.
Removed an unnecessary navigation graph and updated the navigation logic to prevent navigating to the same destination if it is already selected.
Resolves #2110
Resolves #2109
This unfortunately reintroduces the race condition bug in osm map view.
reintroduces #2094
=> Refactor: unwrap map graph

gradle/libs.versions.toml
removed CardView, ViewPager2, and osmdroid-wms dependencies as they are no longer in use.
=> Refactor: Remove unused dependencies

app/src/main/java/com/geeksville/mesh/ui/debug/Debug.kt
Bugfix: 
Text is too long especially when localised. 
Move to icons.
=> fix: Drop text buttons in favor of icons

.gitignore, app/src/main/java/com/geeksville/mesh/model/DebugViewModel.kt, app/src/main/java/com/geeksville/mesh/ui/debug/Debug.kt, app/src/main/res/values/strings.xml
Add useful filters
improve code readability
=> feat:add extra filters, including own address

app/src/main/java/com/geeksville/mesh/ui/metrics/DeviceMetrics.kt, app/src/main/java/com/geeksville/mesh/ui/metrics/EnvironmentMetrics.kt, app/src/main/java/com/geeksville/mesh/ui/metrics/PowerMetrics.kt, app/src/main/java/com/geeksville/mesh/ui/metrics/SignalMetrics.kt
Reverts meshtastic/Meshtastic-Android#2182
mistakenly merged - untested
=> Revert "Fix/2100 graph labels"

app/src/main/java/com/geeksville/mesh/ui/debug/Debug.kt, app/src/main/java/com/geeksville/mesh/ui/debug/DebugSearch.kt
- Improve `DebugSearchState` Composable:
- Add `modifier` parameter
- Apply background color from theme
- Enable custom filter text input
replaces #2218
=> Refactor DebugSearch.kt

app/src/main/java/com/geeksville/mesh/ui/message/components/MessageActions.kt, app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt, app/src/main/java/com/geeksville/mesh/ui/message/components/Reaction.kt, app/src/main/java/com/geeksville/mesh/ui/node/components/NodeChip.kt, app/src/main/res/values/strings.xml
Extracts `ReactionButton`, `ReplyButton`, `MessageStatusButton` and `MessageActions` composables from `Reaction.kt` and `MessageItem.kt` into a new `MessageActions.kt` file.
This change also updates `NodeChip` to use `ElevatedAssistChip` for better visual consistency.
=> Refactor: Extract MessageActions components

app/src/main/java/com/geeksville/mesh/ui/debug/Debug.kt, app/src/main/res/values/strings.xml
#2230 
Add a warning before wiping all your logs. 
This way I'll actually still have data to test my graph changes too.
=> Add warning dialog before clearing logs

.github/workflows/dependency-submission.yml
Enable build scan publishing for dependency submission workflow.
=> chore(ci): Update dependency-submission.yml

app/src/main/java/com/geeksville/mesh/repository/radio/MockInterface.kt
Add some valid sim packets for data not already present.
Done, added mock anonymised values.
=> add some extra sim packets

README.md
make obtanium more visible, deemphasize google
=> redo the beta program links.

app/src/main/res/values-fr/strings.xml, mesh_service_example/src/main/res/values-fr/strings.xml
This PR includes automated updates from the scheduled workflow:
- Updated `firmware_releases.json` from the Meshtastic API (if changed).
- Updated `device_hardware.json` from the Meshtastic API (if changed).
- Source strings were uploaded to Crowdin (if any local changes were pushed).
- Latest translations were downloaded from Crowdin (if available).
Please review the changes.
=> chore: Scheduled updates (Firmware, Hardware, Translations)

.github/workflows/pull-request.yml
I think that'll do it, it just needs a clean exit code,
=> skip test and lint on automated branch

.github/workflows/merge-queue.yml, .github/workflows/pull-request.yml
Adds a single check to the end of the workflow, that determines whether or not it can be merged.
=> single check

app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt
update fequency start, end, and calculations to better match firmware implementation
uses https://github.com/meshtastic/firmware/blob/master/src/mesh/RadioInterface.cpp for reference.
initiated from [discord conversation](https://discord.com/channels/867578229534359593/871539863307055134/1396578183079399475)
=> feat: match fw RegionCode freq precision

.github/workflows/reusable-android-build.yml, app/build.gradle.kts, config/copyright.txt, gradle/libs.versions.toml
Sets up [Spotless](https://github.com/diffplug/spotless) with [ktfmt](https://github.com/facebook/ktfmt)
Sets `ratchetFrom` to `origin/head` so that we can improve incrementally.
Adds license header check and `copyright.txt`
Also adds task to create a SpotlessApply precommit hook - which does a autoformatting pass prior to commit
=> chore(spotless): apply code style improvements and formatting

app/src/main/java/com/geeksville/mesh/ui/common/components/ScannedQrCodeDialog.kt
Added a visual of all changes being made to the LoRa config. Additionally, we now respect the user's OKToMQTT choice, which remains unchanged regardless of the imported LoRa configuration.
=> Added lora config changes to ScannedQrCodeDialog

app/src/main/java/com/geeksville/mesh/ui/message/Message.kt, app/src/main/res/values/strings.xml
This pull request introduces a toggleable "Quick Chat" feature
- https://github.com/meshtastic/Meshtastic-Android/issues/2448
[Screencast_20250726_192418.webm](https://github.com/user-attachments/assets/37663c06-e116-4947-9f32-1169ff250079)
=> feat(ui): move quick chat menu to topBar

app/src/main/java/com/geeksville/mesh/ui/debug/Debug.kt
closes #2554 2554 
Add a weight to the column that must have been lost somewhere,
=> Fix Debug panel: Decoded payload not showing

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/map/MapView.kt, app/src/main/java/com/geeksville/mesh/ui/map/MapViewWithLifecycle.kt
Fixes https://github.com/meshtastic/Meshtastic-Android/issues/2552 by updating MapView to calculate its initial bounding box from the filtered node list.
=> fix/2552 Calculate initial mapView from filtered node list 

app/src/fdroid/java/com/geeksville/mesh/android/GeeksvilleApplication.kt, app/src/google/java/com/geeksville/mesh/android/GeeksvilleApplication.kt, app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
Make datadog respect the analytics toggle.
=> feat(datadog): datadog init tweaks

app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
=> Make overflows on Connections bar nice, and add previews

app/src/main/java/com/geeksville/mesh/ui/metrics/TracerouteLog.kt
=> closes #2646: fix UI overlap on traceroute delete

AGENT.md
Add a new document detailing the architecture, modules, build commands, testing strategy, CI/CD setup, and version control information for the Meshtastic-Android project.
to be used for agentic AI
=> docs: add AGENT.md

app/src/main/java/com/geeksville/mesh/ui/Main.kt, app/src/main/java/com/geeksville/mesh/ui/common/theme/CustomColors.kt
The send color is changed from StatusOrange to StatusGreen and the receive color is changed from StatusYellow to StatusBlue. A new color, StatusBlue, is added to the custom color scheme.
=> fix(UI): update send and receive colors

app/src/main/java/com/geeksville/mesh/service/MeshService.kt, app/src/main/res/values/strings.xml
=> fix(regression): replace lost ringtone and canned message handling

.github/workflows/pull-request.yml
branch selection on workflow manual run
=> chore(ci): remove custom commit message for Crowdin updates

app/src/main/java/com/geeksville/mesh/ui/debug/Debug.kt
- Doesn't seem to have ever done anything - the copy exists, so it's not really needed. 
- Rearrange fnctions so previews are at the end.
=> Fix/debug panel - remove redundant saveOne

app/src/main/assets/firmware_releases.json
This PR includes automated updates from the scheduled workflow:
- Updated `firmware_releases.json` from the Meshtastic API (if changed).
- Updated `device_hardware.json` from the Meshtastic API (if changed).
Please review the changes.
=> chore: Scheduled updates (Firmware, Hardware)

app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt, app/src/google/java/com/geeksville/mesh/ui/map/MapViewModel.kt
This commit introduces support for loading and displaying GeoJSON files as map layers, in addition to the existing KML/KMZ support.
- Added `GeoJsonLayer` handling in `MapView` and `MapViewModel`.
- Updated the file picker to accept GeoJSON MIME types (`application/vnd.geo+json`, `application/geo+json`, `application/json`).
- Introduced a `LayerType` enum to differentiate between KML and GeoJSON layers.
- Modified `MapLayerItem` to include `geoJsonLayerData` and `layerType`.
- Updated logic for adding, removing, and loading layers to handle both KML and GeoJSON types.
- File extension is now used to determine layer type when loading persisted layers and adding new layers.
- Renamed `kmlFilePickerLauncher` to `filePickerLauncher` for clarity.
- Renamed …
=> feat(map): add support for GeoJSON map layers

app/src/main/java/com/geeksville/mesh/repository/radio/StreamInterface.kt, app/src/main/java/com/geeksville/mesh/ui/Main.kt, app/src/main/java/com/geeksville/mesh/ui/common/components/IndoorAirQuality.kt, app/src/main/java/com/geeksville/mesh/ui/intro/NotificationsScreen.kt, app/src/main/java/com/geeksville/mesh/ui/message/Message.kt, app/src/main/java/com/geeksville/mesh/ui/node/components/NodeStatusIcons.kt, app/src/main/java/com/geeksville/mesh/ui/settings/radio/components/AudioConfigItemList.kt, app/src/main/java/com/geeksville/mesh/ui/settings/radio/components/PacketResponseStateDialog.kt
Updates deprecated (mostly) Compose to use recommended updated methods, classes, overloads, etc.
=> refactor: clean up deprecations using recommendations

.github/workflows/release.yml
=> fix(release): release notes path

.github/workflows/release.yml
=> fix(ci): release status condition in workflow

.github/workflows/release.yml
=> fix(ci): release whatsnew path

app/build.gradle.kts, app/src/main/java/com/geeksville/mesh/repository/radio/StreamInterface.kt
it breaks things - try again later.
=> chore(datadog): Disable automatic compose instrumentation

app/src/main/java/com/geeksville/mesh/ui/common/components/EditListPreference.kt, app/src/main/java/com/geeksville/mesh/ui/settings/radio/components/LoRaConfigItemList.kt
removed as broken and has been deprecated
closes #2906
=> Fix #2906 - remove Lora.ignore_incoming

app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt, app/src/google/java/com/geeksville/mesh/ui/map/components/MapControlsOverlay.kt
=> Add active tracking functionality to gmaps

app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt, app/src/main/java/com/geeksville/mesh/ui/settings/components/SettingsItem.kt, app/src/main/java/com/geeksville/mesh/ui/settings/radio/RadioConfig.kt, app/src/main/java/com/geeksville/mesh/ui/settings/radio/components/WarningDialog.kt
Cleans up remaining radio config/settings sections
|------|-----|
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/4f1245c7-1eb4-4995-8396-4fa504db11c4" />|<img width="300" alt="image" src="https://github.com/user-attachments/assets/e8cf76b9-ff32-4652-9d37-8a616544efcb" />|
=> Align syle of admin settings

app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt, app/src/google/java/com/geeksville/mesh/ui/map/MapViewModel.kt, app/src/google/java/com/geeksville/mesh/ui/map/components/MapButton.kt, app/src/google/java/com/geeksville/mesh/ui/map/components/MapControlsOverlay.kt
Replaces broken `DisappearingScaleBar` with static `ScaleBar` - bottom start aligned.
Hides sdk compass element - replaces with rotatey icon in our own MapsControlOverlay.
Removes convoluted camera state logic.
=> refactor(map): fix scalebar and compass

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/ui/settings/SettingsScreen.kt, app/src/main/res/values/strings.xml
Add export all, make the functions more generic. 
Also fix the file naming - closes #2570
=> feat #2570, Add ExportAll to csv

app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt, app/src/google/java/com/geeksville/mesh/ui/map/MapViewModel.kt, app/src/main/java/com/geeksville/mesh/android/prefs/StringSetPrefDelegate.kt
Fixes a couple of map issues:
- initializes map at  connected device's location - a bit less jarring than starting at `( 0, 0 )`
- fixes #2841 - layer and style persistence issues
=> fix: map regressions

app/src/main/java/com/geeksville/mesh/ui/metrics/EnvironmentMetrics.kt
Updated Radiation Units to uR/h
=> Update EnvironmentMetrics.kt - μR/h

.github/workflows/docs.yml, app/build.gradle.kts, gradle.properties, gradle/libs.versions.toml
migrates config to dokka 2 via: https://kotlinlang.org/docs/dokka-migration.html
=> feat(docs): migrate configs to dokka 2

app/src/main/res/values/strings.xml
Included GeoJSON in list of supported map layer import types.
=> Update strings.xml - Include GeoJSON

.github/ISSUE_TEMPLATE/bug_repor_internal.yml
closes #3079 
Hopefully the list is alphabetical, so it'll appear last on the list.
=> add internal bug report with ch_testing tags

app/src/main/java/com/geeksville/mesh/ui/common/components/TitledCard.kt, app/src/main/java/com/geeksville/mesh/ui/connections/ConnectionsScreen.kt, app/src/main/res/values/strings.xml
=> Re-add "set region" CTA

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/navigation/ContactsNavigation.kt, app/src/main/java/com/geeksville/mesh/ui/Main.kt, app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt, app/src/main/java/com/geeksville/mesh/ui/contact/ContactsViewModel.kt, app/src/main/java/com/geeksville/mesh/ui/sharing/Share.kt
Add `ContactsViewModel` for use by `ContactsScreen` and `ShareScreen`.
=> Decouple contacts nav graph from `UiViewModel`

config.properties
keep local builds up-to-date with current version tags
=> chore(repo): Update VERSION_NAME_BASE to 2.7.2

app/src/main/java/com/geeksville/mesh/model/UIState.kt, app/src/main/java/com/geeksville/mesh/navigation/ChannelsNavigation.kt, app/src/main/java/com/geeksville/mesh/navigation/NodesNavigation.kt, app/src/main/java/com/geeksville/mesh/ui/Main.kt, app/src/main/java/com/geeksville/mesh/ui/sharing/Channel.kt, app/src/main/java/com/geeksville/mesh/ui/sharing/ChannelViewModel.kt
VM code needed by `ChannelScreen` has been added to `ChannelViewModel`.
=> Decouple `ChannelScreen` from `UIViewModel`

.github/workflows/promote-release.yml
support same-stage age increments for closed/open with newer internal commits
=> ci(promote-release): enhance stage promotion logic 

.github/workflows/release.yml
Updated conditions for build steps based on channel input.
=> Refactor build steps to check channel input

config.properties
=> chore: Update VERSION_NAME_BASE to 2.7.3
