- app/src/main/res/values-cs/strings.xml
This one is based on slovak version (Jo, bylo to jednodušší ;)) and some tags are missing: modem_config_short, modem_config_medium, modem_config_long, modem_config_very_long, modem_config_unrecognized. What is recent source of these tags? I will update it later.
> Czech localisation

- app/src/main/res/layout/settings_fragment.xml
(Disclaimer: still very new to Android dev)
On Pixel 3XL when resizing to do split window the text for the crash report checkbox overlaps the text behind it. This just adds a background to that text box
> Set crash report text background

- app/src/main/java/com/geeksville/mesh/model/Channel.kt
Put the channel options into the URL fragment instead of the URL path.
This ensures that the channel options (including the channel key) is
never accidentally leaked to a remote party. This URL format appears to
be backwards compatible, URLs generated in the new form are properly
parsed by the old version. URLs generated by the old version are _not_
parsed by the new version.
Closes #126.
> Put channel options into URL fragments

- app/src/main/java/com/geeksville/mesh/android/ContextServices.kt
- app/src/main/java/com/geeksville/mesh/service/SafeBluetooth.kt
- app/src/main/java/com/geeksville/mesh/service/SerialInterface.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
Rather than calling the Android interfaces, I made some read-only extension properties to easily (and consistently) call the system services.
I also fixed some code that assumed BluetoothManager to never be NULL.
The consuming code of the `UsbManager` assumes that the `UsbManager` is always there, so I enforced that too.
> Simplified calls to system services

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
This should ensure that the first character of the long name is retained when forming short names even if it is a vowel.
> Always keep first character of long name when making short name

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/android/ContextServices.kt
- app/src/main/java/com/geeksville/mesh/service/BootCompleteReceiver.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceBroadcasts.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceLocationCallback.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceSettingsData.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceStarter.kt
- moved `MeshService` start-related code to `MeshServiceStarter`
- moved `LocationCallback` to `MeshServiceLocationCallback`
- coroutine scope is now handled in `MeshService` position callback
- refactored `onLocationResult()` to be easier to read
- created `MeshServiceNotifications` for creating and updating of notifications
- moved `SavedSettings` to `MeshServiceSettingsData`
- some renames for consistency, like `MeshService.startService()` versus `MeshService.startServiceLater()`
- misc. cleanup of `MeshService`
When `MeshServiceLocationCallback.onLocationResult()` is called, the code is now not _entirely_ ran on the coroutine scope anymore. Only the actual sending of the message is now done in this scope. This call still happens inside of `MeshService` and not in the location callback …
> Refactored MeshService

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/res/layout/adapter_message_layout.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
This is how it looks: 
Mostly UI changes to the layout, but there are also code changes:
* Update myNode LiveData when messages are loaded from the storage, otherwise the UI will not classify messages correctly until BT connection is established
* Manually set colors/margins in the code
> Material design for Message UI

- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
* Made the radio button that represents the currently selected device to be enabled (or disabled)  based on whether the device is currently connected (or not). 
* Factored the radio button update code into a function and call this function when connection changes (so that the radio button state reflects device connection status)
> Fix radio button enabled/disabled state

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
- app/src/main/res/values/strings.xml
* Split notification channel into 'service' and 'messages' notifications. With a separate channel, we can reasonably enable sounds for incoming messages, otherwise it will be too annoying, as service notifications are very frequent.
* Added deduping for service notifications to reduce their frequency, but in the end it proved not sufficient, so went for the split channel option.
* Provided separate "notification" methods for messages and service, to make things look cleaner.
* Removed recentReceivedTextPacket member, seemed a bit hacky.
> Add a separate notification channel for messages

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt
Fixes for issues discovered during testing map updates
* The isViewVisible workaround for mapbox crashes was not working as expected, as isViewVisible was false all the time (and not updating the map). Rather than fixing the expression for it, I tested on my devices without the workaround and the crash does not happen. I suggest we try to release without the workaround (this PR)
* Follow up to recent change to allow increasing frequency of position broadcast:  
** update gps wakeup frequency, otherwise we were sending the same position all the time.
** shorten period of owner updates according to broadcast frequency (I wish we had an independent period for owner updates..)
* Do not ignore position updates for our device
* Zoom map camera to user location only once, afterwards if user …
> Map UI update fixes

- app/src/main/java/com/geeksville/mesh/DataPacket.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- Adds `hopLimit` to the `DataPacket` class
- Updates `MeshService` to use `DataPacket.hopLimit` when it constructs its `MeshPacket`s
I didn't sanitize the `hopLimit` value, not sure if that is desired.
> Add hopLimit to the DataPacket class

- app/src/main/res/values/strings.xml
The 'Firmware update required' modal contains an expired link to the
Wiki. This commit points the user towards the Firmware Installation
section on Github instead.
* app/src/main/res/values/strings.xml
> Fix expired link

- app/build.gradle
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
Issue: "Brazilian Portuguese (pt-BR)" language loading "Portuguese (pt)" localization files.
Fix: 
- app/build.gradle: Added "pt-rBR" to "resConfigs" line;
Other changes to localization:
- app/src/main/res/values-pt-rBR/strings.xml: various minor changes;
- app/src/main/res/values-pt/strings.xml: copied missing lines 72-114 from updated "pt-rBR" localization.
> Fix: Localization for pt-BR

- app/src/main/res/layout/channel_fragment.xml
Related to Issue [#326](https://github.com/meshtastic/Meshtastic-device/issues/326) in Meshtastic-device.
+ Removed the hint for the Channel Name text field.
+ Removed the hint for the filled_exposed_dropdown text view.
This removes the ghosting as seen [here](https://meshtastic.org/assets/files/android-change-channel-92c9ab05f305ce0d36c8aa208afbc2ba.png) in the docs for the Android app usage.
> removed hints from channel inputs

- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/res/layout/messages_fragment.xml
ENTER/ characters could be sent with textMutiLine & IME_ACTION_DONE.
Fix:
- EditText: Define "SEND" IME Action & InputType "Text" to disable ENTER/ input in message text;
- messageInputText: declare textMultiLine to keep multi-line layout;
- sendButton: minor cosmetic layout changes.
> Fix: sendButton / EditText

- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
bug introduced in release 1.2.50 broke `EditText` calls with `IME_ACTION_DONE`.
PR #293 failed to notice `EditText.on(...)` (line 31-41) isn't local, so changes affected calls from outside MessagesFragment.
- reverted changes to `EditText.on(...)`;
- added `EditText.onActionSend(...)` with custom settings only for calls from MessagesFragment.
> Fix: PR#293 broke IME_ACTION_DONE

- .github/workflows/android.yml
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- build.gradle
Fixes:
- Mapbox gradle secrets
- update gradle `unmockplugin` to 0.7.9
- revert https://github.com/meshtastic/Meshtastic-Android/commit/56fd43e6f5f27f69b36260a3bcc141028dc1c4c9 in `SettingsFragment.kt`: string `short_firmware_version` --> `cur_firmware_version`
> Fix: Android CI / Test

- app/src/main/res/layout/messages_fragment.xml
increase message maxLength to 228 characters (from 200).
in theory 237 should be max, but 234 appears to be the max for Android App and 228 for iOS App.
using 228 to match iOS.
> increase message max length to 228 chars

- .github/workflows/release.yml
previous "latest release" filter excluded firmware pre-releases. this change will use the latest device firmware, including pre-releases, for the OTA firmware update feature and keep device vs. Android versions closer and more compatible.
> include firmware pre-releases in android release build 

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
when NodeInfo is recreated by `installNodeInfo`, only `user` and `position` are updated.
this change adds `lastHeard` and prevents a `?` showing for every node until a new packet is received.
> add lastHeard to installNodeInfo

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
Issue #275
switching across all tabs with `smoothScroll` animations could create a race condition (with mapbox throwing exceptions) while trying to render all fragments at the same time (plus Bluetooth threads).
fix: `smoothScroll: false`
> fix tabLayout smoothScroll crash

- app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- start MeshService `setupLocationRequests` (to use phone GPS) when preference is enabled;
- attach Settings tab `provideLocationCheckbox` to call MeshService `setup/stopLocationRequests`;
- disable "Provide location to mesh" checkbox if Google Play Services is not available (prerequisite).
> add provideLocation service start/stop

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/service/BluetoothInterface.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/main/res/drawable/ic_twotone_add_24.xml
- app/src/main/res/layout/settings_fragment.xml
https://developer.android.com/guide/topics/connectivity/companion-device-pairing 
- no location requirements for device pairing on Android 8+ (API level 26+)
Classic device scan/discovery
- added button press & 5 sec timer for legacy scan
various UI & user notification changes to handle both methods
- common "add" button to search and select devices
> add companion device pairing

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
some Android 12 devices crash when legacy Bluetooth permissions are used.
> fix permissions for android >= 31

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- send position if local node last position has latitude & longitude == 0.0 (ignore `positionBroadcastSecs`)
- remove checks for `location_share LocDisabled` & `fixed_position true` (send position if feature is checked)
---
for now it is recommended to disable location broadcast on the device using the python CLI (not from the app):
`meshtastic --set location_share LocDisabled`
or the device can interfere by also sending position packets.
> fix restrictions to "Provide location to mesh"

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt
- app/src/main/res/layout/advanced_settings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
added switches to all settings
- Broadcast position period: location_share LocEnabled/LocDisabled
- Device sleep period: is_power_saving
- is_always_powered (changed from checkbox to switch)
- removed "0 to disable" logic and text strings
TODO: disable sleep settings from non-ESP32 devices
> add is_power_saving to advanced settings

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/android/ContextServices.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- update permissions for Android 12 (API31+): use `BLUETOOTH_CONNECT` & `BLUETOOTH_SCAN` and don't expose legacy Bluetooth permissions.
- prepare for Android 12 requirements (`targetSdkVersion 31`)
add/update permission calls:
- Minimum: requested at app start
- Bluetooth connect: runtime (request before connect)
- Bluetooth scan: runtime (add/change devices)
- Camera: runtime (QR code scanner)
- Location: runtime (provide location to mesh)
- Background location: runtime (provide location to mesh on Android 11+)
> update permissions for Android 12 (API 31+)

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/ApplicationModule.kt
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/MeshUtilApplication.kt
- app/src/main/java/com/geeksville/mesh/database/DatabaseModule.kt
- app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt
- app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt
- app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/DebugFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- build.gradle
Uses [Hilt](https://dagger.dev/hilt/) to get the database initialization off of the main thread.
The initial introduction always has a disproportionate fan-out of boilerplate.  In this case, all entry points which
were using `UIViewModel` needed to be annotated in order to let the code gen know that they needed to support
it.
The `PacketRepository` is injected into things via the main thread (e.g., the `MeshService`) but due to the
lazy declaration, the database isn't hydrated until the DAO is access while on an IO thread.
> Introduce Hilt dependency injection

- app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt
- app/src/main/java/com/geeksville/mesh/database/entity/Packet.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
A few distinct improvements:
- NodeInfo packet data is used to obtain position information
- "packet"- type packets with position information now fallback to looking for nodeinfo data on the packet
- We no longer cap CSV export to the most recent 500 entries
- Only packets with signal-to-noise values are reported in the CSV
> CSV export improvements to make it more reliable

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/BluetoothViewModel.kt
- app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothBroadcastReceiver.kt
- app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothRepository.kt
- app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothRepositoryModule.kt
- app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothState.kt
- app/src/main/java/com/geeksville/mesh/service/RadioInterfaceService.kt
Changes:
- Adds support for obtaining bonded devices
- Adds support for obtaining BLE scanner
- Consolidates state into a single, immutable data class instance
- Simplified and renamed broadcast receiver
- Renamed view model permissionsUpdated fun to identify the intended use
> Issue #369 - Expand bluetooth repository use cases

- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/res/drawable/ic_twotone_delete_24.xml
- app/src/main/res/drawable/ic_twotone_select_all_24.xml
- app/src/main/res/layout/adapter_message_layout.xml
- app/src/main/res/menu/menu_messages.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Adds action mode menu: `menu_messages` with `delete` & `select all` icons
- longpress message to select & activate menu
- click message to select/unselect
- `select all` icon: select/unselect all messages
- `delete` icon: delete single/multiple/all messages
> add action mode menu to messages (delete & select all)

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/SoftwareUpdateService.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- update spiffs to littlefs
- call `setFirmwareUpdateFilename` before generating `MyNodeInfo` (makes `couldUpdate` more reliable)
- add analytics events for `firmware_update`: start/success/failure
- better firmware update progress bar feedback (smooth transition between littlefs/appLoad from 0% to 100%)
> improve firmware update

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ht/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ko-rKR/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-no/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
- only consider sleep connection state when isPowerSaving is enabled (sleep is now disabled by default)
- update `not_connected` string
> Issue #392 - fix connected but sleeping text to reflect actual device state

- app/src/main/java/com/geeksville/mesh/ui/MapFragment.kt
`binding` is only set in `onCreateView` when analytics are
enabled, leading to a crash in `onViewCreated` when
`binding` - a lateinit var - is attempted to be accessed.
> MapFragment crashes if analytics are not allowed

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/repository/usb/ProbeTableProvider.kt
- app/src/main/java/com/geeksville/mesh/repository/usb/README.md
- app/src/main/java/com/geeksville/mesh/repository/usb/UsbBroadcastReceiver.kt
- app/src/main/java/com/geeksville/mesh/repository/usb/UsbRepository.kt
- app/src/main/java/com/geeksville/mesh/repository/usb/UsbRepositoryModule.kt
- app/src/main/java/com/geeksville/mesh/service/BluetoothInterface.kt
- app/src/main/java/com/geeksville/mesh/service/InterfaceFactory.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MockInterface.kt
- app/src/main/java/com/geeksville/mesh/service/NopInterface.kt
- app/src/main/java/com/geeksville/mesh/service/RadioInterfaceService.kt
- app/src/main/java/com/geeksville/mesh/service/SerialInterface.kt
- app/src/main/java/com/geeksville/mesh/service/TCPInterface.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/main/res/xml/device_filter.xml
Extracts USB device management into a `UsbRepository`.
In order for `SerialInterface to gain access to this prior to
the `RadioInterfaceService` being fully natively dependency
injected, all `InterfaceFactory` implementations needed
to be modified to accept the `UsbRepository` via argument.  This
will go away in a future PR.
Changed `assumePermission` constant to `false` as it was preventing
the request for permission from occurring, breaking serial connectivity.
Minor improvement: `SerialInterface` re-bonding by device name is
now supported.
Another minor improvement:  Adds USB serial connectivity support for TBeam and RAK 4631 devices. 😁
> Initial step in refactoring RadioInterfaceService for dependency injection

- app/src/main/java/com/geeksville/mesh/repository/usb/SerialConnection.kt
- app/src/main/java/com/geeksville/mesh/repository/usb/SerialConnectionImpl.kt
- app/src/main/java/com/geeksville/mesh/repository/usb/SerialConnectionListener.kt
- app/src/main/java/com/geeksville/mesh/repository/usb/UsbRepository.kt
- app/src/main/java/com/geeksville/mesh/service/SerialInterface.kt
- app/src/main/java/com/geeksville/mesh/service/StreamInterface.kt
This separates the USB serial connectivity implementation
out of the radio service.  `SerialInterface` now only deals with
radio service concerns.
Eventually I'd like to see this be more of a sealed class- based state machine feeding into a StateFlow that the UI could drive off of.  For now I want to set that desire aside to keep progressing on dependency injection.
> Extract USB serial communication into USB repository

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/android/ContextServices.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/BluetoothInterface.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/IRadioInterface.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/InterfaceFactory.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/MockInterface.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/NopInterface.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/SerialInterface.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/StreamInterface.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/TCPInterface.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/RadioInterfaceService.kt
- app/src/main/java/com/geeksville/mesh/service/RadioNotConnectedException.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
Continuing work on #369 
This pair of commits simply creates the `repository/radio` dir and moves the radio service code into that new location.
Doing this in a dedicated PR to make the next steps more clear/transparent.
Future/next steps:
- Converting the AIDL `IRadioInterfaceService` / `RadioInterfaceService` from a `Service` into a vanilla object instance.  Using services implies RPC calls - an expensive choice for something not exported outside of the application.
- Native dependency injection of the `InterfaceFactory` instances and `RadioInterfaceService` itself.
- Conversion of `RadioInterfaceService` into a proper repository form.
> Prep work for radio service repository

- app/src/main/java/com/geeksville/mesh/android/ContextServices.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/BluetoothInterface.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
`Settings tab`: add a persistent device list from previous associations ("device history"):
+ adds another option to connect to devices from the list;
+ to remove devices from the list, `forget pairing` in Android Settings.
> add device association list

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/RadioRepositoryModule.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/RadioRepositoryQualifier.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
Slowly continuing work on #369:
In preparation for replacing the `InterfaceFactory` with an
injectable form we need to convert static methods that call
`InterfaceFactory` into non-static, injected forms.
Also:
- Updated kotlin `-Xopt-in` to `-opt-in` to remove build
time warnings.
- Removed some unused `RadioInterfaceService` code.
> Extract `RadioInterfaceService` companion object functions

- app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt
- app/src/main/res/layout/advanced_settings.xml
- app/src/main/res/values/strings.xml
add `Shutdown` & `Reboot` buttons to advanced settings
- send admin packets `shutdown_seconds` and `reboot_seconds` with value of 5 seconds
Note: only sent to the local node but can be expanded to remote nodes.
> add shutdown & reboot buttons

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/AdvancedSettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
update MeshService & UIState viewmodel.
- configs are stored as `LocalOnlyProtos.LocalConfig`;
- but exchanged over-the-wire as `ConfigProtos.Config` oneofs.
> update configs to LocalConfig

- app/build.gradle
- build.gradle
This pulls in a new protoc version that has a workaround allowing M1 MacBooks to resolve an intel arch binary (since the arm64 binary for mac is not yet being built).  Without this, M1's cannot build the project.
Bumped the protobuf plugin version as well but it is unrelated.
> Bump protobuf-gradle-plugin to 0.8.18 and protoc to 3.21.1

- app/src/main/res/xml/device_filter.xml
The LILYGO LoRa32 modules that I recently purchased off Amazon use the CH9102F instead of a CP2102.  (The PCB markings are T3_V1.6.1 20210104, the same as one of the images on meshtastic.org)
felHR95/UsbSerial already supports devices using the CDC protocol (which the Qinheng CH9102F adopts), so adding support is as straightforward as adding the VID:PID to device_filter.xml.
> add CH9102F USB serial (used on some tlora-v2-1-1.6 variants)

- app/src/main/java/com/geeksville/mesh/repository/usb/SerialConnectionImpl.kt
Found the issue behind RAK nodes not connecting properly over serial/USB.  It looks like we have to explicitly raise data-terminal-ready and ready-to-send in order to start receiving data.
I found that gem in the source code published for the Serial USB Terminal app.
> Explicitly enable DTR/RTS to fix RAK serial comms

- app/src/main/res/values/strings.xml
Fixes typo and punctuation mistakes on the app introduction screen as suggested by a member on Discord.
> Fixed typo on App Introduction screen

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/android/ContextServices.kt
- app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt
- app/src/main/java/com/geeksville/mesh/repository/bluetooth/BluetoothRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/main/res/values-ko-rKR/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values/strings.xml
- cleanup and update MainActivity permissions to ActivityResult
- replace `ScanPermissions` with `LocationPermissions` for classic scan (only loc is a runtime perm)
- refactor Scan/ConnectPermissions to BluetoothPermissions (both Nearby devices in API 31+)
- keep Nearby devices at app start for now
> refactor permissions

- app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- remove channelSet fom service;
- interface service only with `setConfig` / `setChannel` (getters use the datastore equivalents).
> move ChannelSet out of MeshService

- app/src/main/res/mipmap-anydpi-v26/ic_launcher2.xml
- app/src/main/res/mipmap-anydpi-v26/ic_launcher2_round.xml
Taking a stab at #573 
Added `<monochrome android:drawable="@drawable/ic_launcher2_foreground"/>` in `ic_launcher2.xml` and `ic_launcher2_round.xml` to add support for A13's themed icons per here [Adaptive icons | Android Developers](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app).
I built the apk in Android Studio and tested it with my Pixel 7 Pro running Android 13 and it installed without issue and support for the themed icons were added allowing color to be changed based on wallpaper or as selected.
> Support A13 Themed Icons (close #573)

- app/src/main/java/com/geeksville/mesh/database/PacketRepository.kt
- app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
check for duplicate packet IDs before sending queued messages (so ACK/NAK updates can work).
> fix: replace duplicate packet IDs before sending queue

- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
- app/src/main/java/com/geeksville/mesh/util/LocationUtils.kt
reverts [refactor: replace zoomToNodes with zoomToBoundingBox](https://github.com/meshtastic/Meshtastic-Android/pull/647/commits/4412a5d5aa6752c9bc1c71084c8570f6efea0df1)
> fix: revert zoomToNodes removal

- app/src/androidTest/java/com/geeksville/mesh/ChannelTest.kt
- app/src/main/java/com/geeksville/mesh/model/Channel.kt
- app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt
- app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/components/EditTextPreference.kt
- app/src/main/java/com/geeksville/mesh/ui/components/config/LoRaConfigItemList.kt
- app/src/test/java/com/geeksville/mesh/model/ChannelSetTest.kt
Radio Configuration > LoRa config:
- displays calculated values for `channel_num` and LoRa `frequency` when set to zero (defaults).
> feat: calculate default values for LoRa channel_num and frequency

- app/src/main/res/values/strings.xml
It's not intuitive that the checkbox is referring specifically to the phone's location. This has come up a few times in the Discord, and it feels worth clarifying.
I'm not at all married to the specific wording, but I think it makes sense to tweak this to be more descriptive.
> Provide _phone_ location to mesh

- app/src/main/java/com/geeksville/mesh/database/entity/MeshLog.kt
- app/src/main/java/com/geeksville/mesh/model/Channel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/components/config/PacketResponseStateDialog.kt
Refactor UI to simply consume data from ViewModel improving code organization and separation of concerns:
- generalized `ResponseState` for wider use;
- consolidate state variables into `RadioConfigState`;
- moved config getters/setters processing to ViewModel;
- added error handling for a few extra cases.
> refactor(config): move business logic to ViewModel

- app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/components/config/ChannelSettingsItemList.kt
- app/src/main/java/com/geeksville/mesh/ui/components/config/EditChannelDialog.kt
Simplify the `ChannelFragment` UI channel editor to display all channels on the same tab along with other options instead of opening a separate screen.
> refactor: single-page channel editing

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
This PR moves all logic related to RadioConfig into its own dedicated ViewModel to improve codebase organization and modularity.
> refactor: move RadioConfig logic into separate ViewModel

- app/src/androidTest/java/com/geeksville/mesh/ChannelTest.kt
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/ChannelSet.kt
- app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/test/java/com/geeksville/mesh/model/ChannelSetTest.kt
Refactors the `ChannelSet` class by converting it to `AppOnlyProtos.ChannelSet` protobuf extensions. Eliminates redundant methods and simplifies the process for creating and parsing Meshtastic URLs and QR Codes.
> refactor: convert `ChannelSet` to protobuf extensions

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/repository/network/MQTTRepository.kt
- app/src/main/java/com/geeksville/mesh/repository/network/TrustAllX509TrustManager.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Implements MQTT client proxy functionality, acting as a front-end interface proxy for sending and receiving MQTT messages to and from the radio. Utilizes the Android device's Internet connection extending MQTT access for non-TCP/IP interfaces such as Bluetooth and Serial.
reference: https://github.com/meshtastic/protobufs/pull/363
> feat: implement MQTT client proxy

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/database/dao/MyNodeInfoDao.kt
- app/src/main/java/com/geeksville/mesh/model/NodeDB.kt
- app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/ServiceRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
This PR converts the `NodeDB` class into a singleton repository using Hilt dependency injection. Transitions from a monolithic ViewModel to individual ViewModels tailored for each fragments or screens. This change enhances decoupling and modularity, making the codebase cleaner and easier to use.
> refactor: convert `NodeDB` to repository

- app/src/main/res/layout/dialog_add_quick_chat.xml
#783 Fix of issue for quick message  input.
Currently, the input for the quick message is a single line of text (android:inputType="textShortMessage") this does not correlate with the type of input that is used when writing a message (android:inputType="textMultiLine|textCapSentences") whitch is multiline-capable.
Problem:
With textShortMessage you can only have single line quick message.
Solution:
Change android:inputType="textShortMessage" to android:inputType="textMultiLine|textCapSentences" on line 17 in file app/src/main/res/layout/dialog_add_quick_chat.xml
Also added maxLength="228" acording to @andrekir tip
> #783 Fix of issue for quick message  input

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
Second attempt/approach at fixing #818.
This approach retains the delimiter but uses double quotes around the values, conforming to [RFC4180](https://datatracker.ietf.org/doc/html/rfc4180)
I tested the resulting file by loading it into Excel and Numbers on my desktop, and Google Sheets on my mobile device.
I also tried switching my device language to Norwegian to test the comma as a decimal.  That worked for the fields which were in the immediate code path for generating the CSV.  Things like the lat and lon still had decimal point separators so I'm not sure how far we want to take it, but the CSV is parsed correctly now.
NOTE: I also locally hacked my source to test a message containing a single double quote character and this worked as well.  I had to hack the source because the message …
> Change CSV output to be RFC4180 compliant

- app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt
Adds a bit of padding around the text, as well as rounds the corners a bit for a cleaner look
Before
After
> Map labels - round corners and pad label background

- app/src/main/java/com/geeksville/mesh/ui/BatteryInfo.kt
- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/theme/Color.kt
- app/src/main/java/com/geeksville/mesh/ui/theme/Theme.kt
- app/src/main/res/drawable/ic_battery_alert.xml
- app/src/main/res/drawable/ic_battery_high.xml
- app/src/main/res/drawable/ic_battery_low.xml
- app/src/main/res/drawable/ic_battery_medium.xml
- app/src/main/res/drawable/ic_battery_outline.xml
- app/src/main/res/drawable/ic_battery_unknown.xml
- app/src/main/res/layout/adapter_node_layout.xml
Doesn't completely resolve #826, but addresses the voltage info complaint from @HikerScott 
Primarily, moves the battery info into a composable and uses that in the adapter
I added in a couple more battery icons to get a quick idea of the level. I set the ranges arbitrarily, so we could tune these later to match user expectation better
I also cleaned up the adapter item layout for nodes to avoid manually declaring margins on everything. Additionally, moved the sample text to a tools attribute so it still shows up in the preview, without actually setting the fields in the app
> Improved battery/voltage info in node list

- app/src/main/java/com/geeksville/mesh/ui/BatteryInfo.kt
Used to be 2, and I set it at 1 when refactoring. Reported by @prokrypt [here](https://github.com/meshtastic/Meshtastic-Android/issues/826#issuecomment-1973406585)
> Restore voltage precision to 2 places

- app/src/main/java/com/geeksville/mesh/ui/BatteryInfo.kt
was missed in pull request 889 @ https://github.com/meshtastic/Meshtastic-Android/pull/889
> 2 decimal places for plugged-in voltage

- app/src/main/java/com/geeksville/mesh/util/Extensions.kt
Fixed the issue where 59 minutes would show up as "0 hours"
Ignore my misnamed commit message, lol.
> Fixed 59 minute issue

- app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt
reference: 
- https://github.com/meshtastic/firmware/pull/3403
- https://github.com/meshtastic/firmware/pull/3490
closes #930
> refactor: add fixed position admin messages

- .idea/inspectionProfiles/Project_Default.xml
- app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/6.json
- app/src/main/java/com/geeksville/mesh/NodeInfo.kt
- app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/SignalInfo.kt
- app/src/main/java/com/geeksville/mesh/ui/preview/PreviewParameterProviders.kt
A basic implementation of Hops Away, closing #922 
Modifies SignalInfo, if hopsAway is more than 0 it replaces the RSSI with the number of hops.
> Hops Away implementation

- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- app/src/main/res/menu/menu_nodes.xml
- app/src/main/res/values/strings.xml
Closes #964
Moves Forget Node in the node menu to the bottom, preventing people form pressing it accidentally when trying to traceroute. 
Also adds a dialog box to confirm the action of forgetting a node, similar to ignoring a node.
> Forget node menu changes

- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
I have no idea what I'm doing but this supposedly fixes https://github.com/meshtastic/Meshtastic-Android/issues/982 and part of https://github.com/meshtastic/Meshtastic-Android/issues/691
> Make sure IP Address radio button stays enabled for valid IP

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/ServiceRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- create new state with `wantConfig` information, including node count;
- use state in fragment for more detailed connection status feedback.
closes #1006
> refactor: improve connection status feedback

- app/src/main/java/com/geeksville/mesh/ui/LinkedCoordinates.kt
Currently clicking on a node's location will open up the maps app, but does not 'pin' the real location. 
This change updates the URI used for the Maps intent to pass the coordinates in a way that will place a pin in the native Google Maps as well as 3rd party map applications (like OsmAnd).
Video of fix: 
https://github.com/meshtastic/Meshtastic-Android/assets/1168530/100e6efa-fa6a-42af-8bce-5059fb2580bd
> fix: show maps pin when clicking on node coords

- app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/components/LazyColumnDragAndDropDemo.kt
- app/src/main/java/com/geeksville/mesh/ui/components/config/ChannelSettingsItemList.kt
Adds `LazyList` drag and drop functionality using long-press [gestures](https://developer.android.com/develop/ui/compose/touch-input/pointer-input/understand-gestures).
> feat: add `LazyList` drag and drop functionality

- app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
The hardware information displayed in the NodeInfo view was incorrect(using `thisNodeInfo`). This commit fixes the issue by using the correct node (`thatNodeInfo`) information to retrieve the hardware model string.
> fix: Display correct hardware info in NodeInfo

- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/res/layout/messages_fragment.xml
This updates the message toolbar title to include the channel number and name when viewing direct messages.
This improves the user experience by providing more context about the conversation.
[Screen_recording_20240711_195141.webm](https://github.com/user-attachments/assets/64be42a6-f6dd-4aad-b00c-b83bd229b24b)
resolves #942
> Feat: Show channel number and name in direct message title

- app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
fixes: #1162
Uses IntrinsicSize.Min width to accommodate larger character width.
> fix: NodeInfo chip line wrapping

- app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/MockInterface.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
This commit adds a visual indicator to the map that shows the precision of a node's position. The indicator is
a circle around the node's marker, and the size of the circle corresponds to the precision of the position.
The precision is determined by the `precisionBits` field in the node's position data. The higher the `precisionBits` value, the more precise the position.
This feature helps users to
understand the accuracy of the position data displayed on the map.
This should follow closely with @garthvh 's work on Apple here: https://github.com/meshtastic/Meshtastic-Apple/blob/3fc03b721130f3e295a43ccb06395a466faa464e/Meshtastic/Views/Nodes/Helpers/Map/MapContent/MeshMapContent.swift#L134
closes #893
> feat: Add position precision indicator to map

- app/src/main/java/com/geeksville/mesh/ui/LastHeardInfo.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- app/src/main/java/com/geeksville/mesh/util/Extensions.kt
This introduces a periodic update to the last heard time displayed in the UI. The time is now refreshed every 1 minute
to ensure accurate and up-to-date information.
fixes #1136
> Fix: Periodically update last heard time

- app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/9.json
- app/src/main/java/com/geeksville/mesh/NodeInfo.kt
- app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
As suggested by **https://github.com/meshtastic/Meshtastic-Android/discussions/1138#discussioncomment-10203963**
This adds a new field `role` to the `NodeInfo` entity in the MeshtasticDatabase. The `role` field is an integer with a default value of 0. This change allows the app to store and display the role of a user in the mesh network.
@andrekir - I found the `role` defined in the `User` proto [here](https://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.User), and added it to our local model. Let me know if there's a better/more preferred way to add a field from a proto.
> feat: Add role to NodeInfo

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This commit adds feature request and bug report templates to the repository. It also disables the ability to create blank issues, requiring users to use one of the provided templates.
> chore: Add issue templates and disable blank issues

- app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
This updates precision circles around nodes on the map to better visually represent the accuracy of their positions. The circles are now colored according to the node's color and are now more transparent.
This adds precision circle to the `MarkerLabel` canvas, so it can be managed alongside markers. This fixes the redraw on zoom issue that users were experiencing.
> Fix: Colored transparent precision circles around nodes on map

- app/src/androidTest/java/com/geeksville/mesh/compose/EditDeviceProfileDialogTest.kt
- app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/components/config/EditDeviceProfileDialog.kt
Simplifies and improves state management by dynamically handling field states. Instead of manually managing individual fields, the dialog dynamically generates and tracks the state of each field in the `DeviceProfile` protobuf.
> refactor: update `EditDeviceProfileDialog` using dynamic fields

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
This adds traceroute paths in both directions, including SNR values. This still uses a text dialog, but readability is improved as suggested in #1207. More UI improvements can be added once the functionality can be tested thoroughly with both new and old firmwares.
I've tested this with firmware 2.5 nodes and a routes with a combination of 2.5 and 2.4 nodes, but not using 2.4 nodes exclusively.
> Show results for two-way traceroute, including SNR values between hops

- app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/10.json
- app/src/androidTest/java/com/geeksville/mesh/NodeInfoDaoTest.kt
- app/src/main/java/com/geeksville/mesh/database/Converters.kt
- app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt
- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
- app/src/main/java/com/geeksville/mesh/database/entity/NodeEntity.kt
- app/src/main/java/com/geeksville/mesh/model/NodeDB.kt
- app/src/main/java/com/geeksville/mesh/model/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
This PR aims to decouple the `NodeInfo` API layer from the database by introducing a new protobuf-based entity.
By separating the internal database model from the API representation, this reduces tight coupling and makes it easier to update or modify the internal database without impacting the API. Using protobuf ensures changes to the project's protobuf definitions are available in the database without migrations or schema changes, improving database flexibility and reducing maintenance overhead.
Key changes:
- Introduces a protobuf-based `NodeEntity` as the new Room database entity;
- Replaces `NodeInfo` references with `NodeEntity` in the DAO layer, `NodeDB`, and `MeshService`;
- Decouples `NodeInfo` from the database schema, allowing future changes without impacting the API;
- …
> refactor: introduce `NodeEntity` protobuf-based database entity

- app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt
- app/src/main/java/com/geeksville/mesh/ui/components/IndoorAirQuality.kt
- app/src/main/res/values/strings.xml
Adds Indoor Air Quality (IAQ) to the environment metrics chart and card.
The IAQ is displayed as
a green line on the chart and as a dot with a numerical value on the card.
The IAQ scale is available as a legend in the IAQ component.
> feat: Add IAQ to environment metrics

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/MetricsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt
The temperature values in the
environment metrics charts and cards are now displayed in Fahrenheit or Celsius based on the user's preference.
Celsius is still used as the base unit for calculations and storage.
resolves #1251
> feat: Add ability to display environment metrics in Fahrenheit

- app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/components/config/PositionConfigItemList.kt
This fixes persistent validation errors when setting fixed latitude, longitude and altitude when the Position object is null.
Root issue: state comparison always fails during error checking when passing a literal double or int value into EditTextPreference (in this case 0.0 for lat and lng, and 0 for altitude).
> Fix lat/lng/alt config validation errors when position is null

- app/src/androidTest/java/com/geeksville/mesh/NodeInfoDaoTest.kt
- app/src/main/java/com/geeksville/mesh/database/entity/NodeEntity.kt
- app/src/main/java/com/geeksville/mesh/model/NodeDB.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/LinkedCoordinates.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeItem.kt
- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/SignalInfo.kt
- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/preview/NodeEntityPreviewParameterProvider.kt
- app/src/main/java/com/geeksville/mesh/util/LocationUtils.kt
Continued work on #1250 to decouple the `NodeInfo` API layer from the database by using `NodeEntity`.
> refactor(NodeItem): replace `NodeInfo` with `NodeEntity`

- app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/12.json
- app/src/main/java/com/geeksville/mesh/database/Converters.kt
- app/src/main/java/com/geeksville/mesh/database/MeshLogRepository.kt
- app/src/main/java/com/geeksville/mesh/database/MeshtasticDatabase.kt
- app/src/main/java/com/geeksville/mesh/database/dao/MeshLogDao.kt
- app/src/main/java/com/geeksville/mesh/database/entity/MeshLog.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- Adds `from_num` and `port_num` fields as indices to the `MeshLog` entity to improve query performance.
- Adds `fromRadio` protobuf field for data storage.
- Sets default values for new columns for auto-migration and backward compatibility.
> refactor(MeshLog): add fields for query optimization

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Fix for client requests stalling when firmware rate limit is triggered. Completes the request future per the `replyId` in the `ClientNotification` response. I'm not sure if this is the optimal solution considering how client notifications may be used in the future, but it solves the issue for now. If I can rework the fix, let me know!
> Complete request future if response is a ClientNotification

- app/src/main/java/com/geeksville/mesh/ui/NodeItem.kt
This commit adds elevation to the NodeItem card to visually distinguish it.
This also better visually aligns to the channel/user cards 4dp elevation, maintaining consistency.
resolves #1246
> fix: Add elevation to NodeItem card

- app/src/main/java/com/geeksville/mesh/ui/components/IndoorAirQuality.kt
Adds IAQ ranges and colors to the `Iaq` enum and updates the display to show the ranges alongside the
descriptions, improving clarity for users.
This change enhances the indoor air quality information by providing context for the different IAQ levels.
Also updated the color values to match the chart [here](https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BME680-688-IAQ-meaning/m-p/45204)
> refactor: Improve IAQ display to add ranges, update colors

- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
Nodes with -1 hops (unknown) are now sorted last when sorting by `Hops Away`.
fixes #1301
> fix: sort nodes with unknown hops last

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
fixes: #1304
The calculation of `hopsAway` was using an incorrect comparison between `hopStart` and `hopLimit`. This commit fixes the logic to correctly determine the number of hops a packet has traveled.
> fix: Correctly compare hopStart and hopLimit for received packets

- app/src/main/java/com/geeksville/mesh/ui/SignalInfo.kt
This replaces the string "unknown" with a question mark `?` when displaying the hop count for a
node if the hop count is unknown `-1`. This provides a more concise and visually clear indication of an unknown hop count.
fixes #1306
> fix: Replace "unknown" with "?" for unknown hop count

- app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
On my phone, I have 5 devices linked.  They currently appear like so:
I'd prefer that they at least displayed in alphabetical order, while maintaining "None (disable)" at the top of the list. 
Here are before and after using the simulator:
> feat: sort device list while keeping None (disable) at the top of the list

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
- app/src/main/res/values/strings.xml
Proposed change:  I'd like to know when a new node is seen/added to the NodeDb
Adds new Android notification when new node is seen.
resolves #914
> feat: Add notification for new node seen

- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
Adds a chronometer to the service notification, counting down to the next stats update. Also adds timestamps to the service notification, message notification, and new node seen notification.
[Screen_recording_20241017_180802.webm](https://github.com/user-attachments/assets/442369ea-0be8-4909-aba7-d73abed91e91)
> feat: Add chronometer and timestamp to notifications

- app/src/main/java/com/geeksville/mesh/database/MeshLogRepository.kt
- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/DeviceSettingsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeDetailsScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/components/CommonCharts.kt
- app/src/main/java/com/geeksville/mesh/ui/components/DeviceMetrics.kt
- app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt
- app/src/main/java/com/geeksville/mesh/ui/components/LoraSignalIndicator.kt
- app/src/main/java/com/geeksville/mesh/ui/components/SignalMetrics.kt
- app/src/main/res/values/strings.xml
Added a signal graph that plots the rx snr and rssi of a mesh packet.
- Moved the time labels above and outside of the graph area.
- Implemented info dialogs for all existing graphs.
- Implemented a signal indicator to visualize the signal quality for each data entry.
Retrieving the data from the DB, do I need to filter anything out with respect to hops or from?
Planning on completing this during the review.
- Since we don't receive mesh packets from our connected node, the nav card shouldn't be available when clicking on More details for our nodes.
> Signal Metrics

- app/src/main/java/com/geeksville/mesh/model/Message.kt
- app/src/main/java/com/geeksville/mesh/model/NodeDB.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
fixes #1349
This commit updates the `getUser` function in `NodeDB` to set the ID of the user when creating a new `User` object, ensuring that the user ID is always populated.
Additionally, it refactors the `Message` class to use the proto `User` object instead of the `MeshUser` class. This change simplifies the code and improves consistency by utilizing the proto definition for user information.
> fix: Display for self-sent messages

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
I try to avoid having notifications on for pretty much any Android app unless absolutely necessary, and having the snackbar continuously asking me to give the notification permission to Meshtastic is very annoying, especially since I have to keep dismissing it when switching between apps.
Change the duration from INDEFINITE to SHORT for those messages.
> Short duration for the "notification permissions denied" snackbar

- README.md
I felt that build instructions weren't clear enough. So I've tried to rephrase it to be more clear.
my changes:
- made it ordered list;
- added bash scripts;
- requiring git cloning;
- added sub-step to open directory;
- added URL to Android studio;
- removed list member to be just bottom text;
- made "Note:" bold;
> Updated build instructions in README.md

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt
- app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt
- app/src/main/java/com/geeksville/mesh/ui/components/TracerouteLog.kt
- Consolidates `MetricViewModel` back to a single state flow
- Introduces a `MutableStateFlow` for state updates, allowing more independent control
- Moves `Telemetry`, `MeshPacket` and config updates into separate coroutines
> refactor: split `MetricsViewModel` state updates

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
Deduplicate position logs by filtering out duplicates based on time and location.
Note: this just deduplicates the list presented to the UI, not the stored logs/packets.
From conversation: https://discord.com/channels/867578229534359593/1039674919346249728/1307512271320252487
> Fix: Deduplicate position logs

- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- config/detekt/detekt-baseline.xml
IPhone app uses 200 chars as it's message limit.
This was last updated after the introduction of PKI. Testing there revealed that with PKI the real max now is about 225, but reliability starts to dip before then. I confirmed this in testing wirh Android on a few devices just now.
Change Android app to match iPhone.
> Change max message length to 200

- .idea/inspectionProfiles/Project_Default.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/Message.kt
- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/ShareFragment.kt
- app/src/main/res/layout/share_fragment.xml
- app/src/main/res/values/strings.xml
This PR adds a text/plain intent that allow user to share a piece of text to a Meshtastic node through the application.
This PR is currently a WIP. As of right now, only the intent was added. 
The PR idea would be 2 fold:
1. Add a way to easily share the text to a user-selected contact. For this, I thought of adding an optional `txtToFill` variable to the [`navigateToMessages`](https://github.com/meshtastic/Meshtastic-Android/blob/227c65f1914cd5b4b379e94070bafc0463b08eb5/app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt#L40) function (or create a new function altogether). If not empty, this variable would autofill the text input of the selected contact.
2. Create some kind of JSON struct that would be auto parsed, like 
```json
{
"contactKey": string,
"contactName": string, …
```
> feat: add text/plain intent to send message 

- app/src/main/java/com/geeksville/mesh/ui/ContactsFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt
- app/src/main/res/drawable/ic_twotone_content_copy_24.xml
- app/src/main/res/menu/menu_messages.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Implements feature request: #1358
Adds action to copy selected message(s) to the clipboard. Unfortunately there is place for only 3 icons (at least on my device) that are already there. Adding 4th pushes two icons to overflow menu, so only 2 icons are visible (third is overflow menu icon).
I also had to style the overflow menu and back button's icons. They weren't visible on dark theme.
That's my first PR. Any feedback is appreciated!
> Feature: Copy message to clipboard

- app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
- app/src/main/java/com/geeksville/mesh/service/SafeBluetooth.kt
This pull fixes two issues.
1.  The necessity to click None before manually selecting a reconnect from the BT device popup.
2.  The prolonged disconnection non-reconnect behaviour is fixed by trapping BT disconnect code 147 and calling lostConnection() function.  This sets up a reconnect attempt loop every 30 seconds. This might be power draining. Could add a user preference somewhere to do this or not. Built apk is available here for testing : https://wildc.net/tmp/meshtastic-fdroid-debug.apk
> Bluetooth reconnect fix android15

- app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt
- Device details section visible only if device hardware is available.
- Added spacing between icon, label, and value in node details rows.
- Right-aligned the values in node details rows for better readability.
Before:
After:
> refactor: Improve device details layout

- app/src/main/java/com/geeksville/mesh/model/DeviceHardware.kt
Use the case versions of heltec v3 and rak 4631 device hardware svg for better visual recognition.
> fix: Use case version of Heltec V3 and RAK4631 board images.

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/components/DeviceMetrics.kt
- app/src/main/java/com/geeksville/mesh/util/GraphUtil.kt
As a start point the time separation threshold was shared across selected time frames. This next step is the beginning of using more appropriate thresholds depending on the time frame selected by the user.
https://github.com/user-attachments/assets/340440d9-e1ce-4002-abb7-88b98a41c26c
https://github.com/user-attachments/assets/319da6f2-b219-4038-906c-13c73fac4212
> Line Breaks According to the TimeFrame

- .github/workflows/android.yml
Adds `GRADLE_ENCRYPTION_KEY` secret to repository, otherwise no configuration cache is saved or restored.
- https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#saving-configuration-cache-data
- https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:secrets
> ci: add Gradle `configuration-cache` encryption key

- renovate.json
Adds `dependencies` label to Renovate dependency update Pull Requests for ease of identification and sorting.
> feat: Add 'dependencies' label to Renovate PRs

- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
Noticed that the filter search sticker header in the users screen had a transparent background, and scrolled items could be seen behind it. This PR just adds a background to the sticky header so that list items can't be seen when scrolled behind it.
| ------- | ------ |
| <video src="https://github.com/user-attachments/assets/d7c3ffa6-d6ff-4525-ae85-ec43fa8f925e" width="300"></video>  | <video src="https://github.com/user-attachments/assets/85ed2df2-3df8-445b-8b59-9aa816e16189" width="300"></video> |
> [Quick UI Update] Apply a background to the filter search sticky header

- app/src/main/java/com/geeksville/mesh/ui/NodeItem.kt
- app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
Adds a simple animation when expanding/collapsing details for user node list items.
| ------- | ------ |
| <video src="https://github.com/user-attachments/assets/7d30d0dc-7069-4808-b0a7-bd3cfe77e6c0" width="300"></video> | <video src="https://github.com/user-attachments/assets/5268e024-d626-442d-b605-a8f6bab2d757" width="300"></video> |
> [Quick UI Update] Animate user node list items on details expansion

- .gitignore
- .idea/icon.svg
- settings.gradle
Updated the project name from "Mesh Util" to "Meshtastic Android", and set project icon for Android Studio/IntelliJ/Toolbox. These changes are all internal to IDEs, no user-app-level facing changes.
| ------ | ------ |
| <image src="https://github.com/user-attachments/assets/7095d364-1d49-4a49-a461-12c6e0959d8b"/> | <image src="https://github.com/user-attachments/assets/ac038131-bd6e-4006-ac81-b4e48eda8f83"/> |
Also shows in Jetbrains Toolbox, which is a nice differentiation if you have a lot of projects:
> [DevEx] Update project name and icon

- app/src/main/java/com/geeksville/mesh/ui/components/NodeFilterTextField.kt
- app/src/main/java/com/geeksville/mesh/ui/compose/preview/LargeFontPreview.kt
Fixes #1561
- Use `defaultMinSize` instead of setting a static height, so that the node filter TextField will accommodate devices with larger font settings
- Add `@LargeFontPreview` annotation for adding a preview with large font enabled
| ----- | ----- |
| <img src="https://github.com/user-attachments/assets/e409bb27-3a09-4d08-96e6-a05df4738df2" width="300"/> | <img src="https://github.com/user-attachments/assets/4e0baded-b0d2-4100-9f87-e330c1bb806a" width="300"/> |
| <img src="https://github.com/user-attachments/assets/1f4f3fb4-ce42-4cea-9e46-c69348872f94" width="300"/> | <img src="https://github.com/user-attachments/assets/7b3aba72-fb47-4d7c-bab3-bfb5574184ef" width="300"/> |
Typing:
<video src="https://github.com/user-attachments/assets/74efd1b8-6bd8-4dd8-aeef-b14296 …
> Fixes #1561: Accommodate large font for node filter

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfig.kt
- app/src/main/java/com/geeksville/mesh/ui/theme/Color.kt
- app/src/main/java/com/geeksville/mesh/ui/theme/Theme.kt
Fixes #1604: Stop overriding `surface` and `onSurface` in our `AppTheme` to remove issues from semi-transparency.
| ------ | ------ |
| <img src="https://github.com/user-attachments/assets/f2c49db9-4851-44d7-b3de-f41ddd32094a" width="300"/>  | <img src="https://github.com/user-attachments/assets/7bd9ef81-1471-4abf-9ce1-c7c0f18cf769" width="300"/>  |
| <img src="https://github.com/user-attachments/assets/bfa4fa44-45cf-4895-860b-626e9c550c68" width="300"/>  | <img src="https://github.com/user-attachments/assets/4c916f24-a17a-4b58-8815-8baf3e3570a3" width="300"/>  |
> Fixes #1604: Stop overriding surface/onSurface in theme

- .github/PULL_REQUEST_TEMPLATE.md
Last PR of the day: I often include screenshots/recordings in my PRs to help reviewers easily see changes. It's nice to have quick templates available for copy/pasting in new PRs to encourage contributors to add these.
Referenced table looks like this in markdown (imagine images are included):
|------|-----|
| <img src="" width="300"/> | <img src="" width="300"/> |
> Include image/video tag examples in PR Template comment

- app/build.gradle
- build.gradle
- gradle/libs.versions.toml
This introduces a version catalog via `libs.versions.toml` to centralize and manage project dependencies. It replaces the previous hardcoded dependency versions in `.gradle` files with references to the version catalog. This change enhances maintainability and organization by centralizing dependency management.
- Added `gradle/libs.versions.toml` to define dependencies, plugins, and their versions.
- Updated `build.gradle` to utilize references from the version catalog,
- Updated `app/build.gradle` to utilize references from the version catalog.
- Removed hardcoded version strings in gradle files.
- Added note and suppressed warning to avoid updating `zxing-core` dependency
- Consolidated dependencies into `[bundles]`
- Refactored to ensure consistency in version catalog definititons and …
> feat: Introduce Version Catalog for Dependency Management

- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
Sets the new message notification time to the time of the received message instead of the time of the app startup.
> fix: New message notifications now correctly show the receive time in the notification drawer

- app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt
Modified NodeDetail.kt to replace direct comparisons with 0f or 0 for sensor values with corresponding has*() functions. This change improves code readability by clearly indicating the presence or absence of sensor data.
> fix: Refactor NodeDetail.kt to use has*() functions

- app/src/main/java/com/geeksville/mesh/ui/components/EditTextPreference.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/LoRaConfigItemList.kt
Fixes #1615
Adds an explicit edit text preference for signed integers, and moves TX power to this preference so that negative values can be set.
|------|-----|
| <video src="https://github.com/user-attachments/assets/8e80f931-6b13-4a61-8109-86b045cd966c" width="300"></video> | <video src="https://github.com/user-attachments/assets/93da5597-0425-4095-9858-7abc678a645e" width="300"></video> |
> fix #1615: Add explicit signed int editing preference

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/res/values/strings.xml
Fixes #1554
Adds content descriptions to main tabs for screen reader support. Also moves to using string resources for these values so that they can be translated.
Apologies for the potato recording, the combo of the device being in TalkBack mode and not being able to record audio from logcat made it easier to just record from my other phone lol:
<video src="https://github.com/user-attachments/assets/0db8ffa9-2bb9-4eab-a641-bffb449da508" width="300"></video>
> fix #1554 (a11y): Add content description to tabs for screen reader support

- app/src/main/java/com/geeksville/mesh/android/ContextExtensions.kt
- app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt
Similar to the change to label text [here](https://github.com/meshtastic/Meshtastic-Android/pull/1630), this PR modifies the map label offset to use DP instead of a static pixel value. This makes sure that any device will have a more uniform offset for the map labels.
I don't have my tablet available atm, but this is before and after on my S23 ultra:
|------|-----|
| <img src="https://github.com/user-attachments/assets/f8a63776-4128-4611-9c96-f23ae3a56df9" width="300"/> | <img src="https://github.com/user-attachments/assets/ded2d53e-7b44-48cc-b4b7-b1eb4b7c1b43" width="300"/> |
> fix #1616: Calculate DP to pixel value for map label offset

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/DeviceConfigItemList.kt
- app/src/main/res/values/strings.xml
Introduced a confirmation dialog that will be shown when changing the device role to "router". The confirmation dialog includes links to the "Device Role Documentation" and "Choosing The Right Device Role" blog post. The user must check a checkbox to confirm.
resolves #1611
> feat #1611: Add confirmation dialog when changing to router role

- app/src/main/java/com/geeksville/mesh/model/Node.kt
Modify the Paxcount display logic to show the string if either `ble` or `wifi` is not zero, rather than requiring both to be non-zero.
fixes #1634 #1552 
thanks for the callout @Donnie650 !
> fix: Update Paxcount display condition

- .github/workflows/android.yml
as suggested in https://github.com/ReactiveCircus/android-emulator-runner/issues/385#issuecomment-2492035091
> fix #1645: Ensure test run completion on Android by killing crashpad_handler

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
The `awesome.app.rating` dependency is now under `googleImplementation` instead of `implementation` in `app/build.gradle`.
fixes #1654
> fix #1654: Move the app rating dependency to googleImplementation

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/DeviceConfigItemList.kt
The role change logic was modified to show a confirmation dialog when the role is set to `ROUTER`, `ROUTER_CLIENT`, or `REPEATER`. Previously, the dialog was only displayed when setting the role to `ROUTER`.
Also the clickable area for the checkbox has been expanded to the full width of the Row.
<video src="https://github.com/user-attachments/assets/e3fd872a-9f34-405f-80b2-2228f4f3c7d8
" width="300"/>
> feat: expand role confirmation to include REPEATER

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Updated the minimum required firmware version to 2.3.15 - [aligns with iOS](https://github.com/meshtastic/Meshtastic-Apple/blob/6e6de4da64facb30120e39b17191243407876ebe/Meshtastic/Helpers/BLEManager.swift#L30).
> chore: Update minimum required firmware version 2.3.2 -> 2.3.15

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
- app/src/main/res/values/strings.xml
Closes #1395 and closes #1598
This PR adds low-battery notifications for both locally-connected and remote nodes that have been added as a favorite in the device's node DB.
Currently, the notification is sent when a device goes below 20% battery remaining, but if a device reports the battery voltage as "0.00" volts, it will be exempt from alerts as that is a magic number in the firmware for no battery voltage support. In the future, this threshold will be configurable, but it is currently fixed.
For now, separate notification channels are created for locally-connected nodes and remote favorite nodes, but in the future this will be grouped together under a single notification channel that has settings to enable or disable reporting of remote favorite nodes.
> feat: Initial implementation of low battery notifications for nodes

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
Noticed some chatter on #1653 and wondered if this might be a potential solve. I changed up the notification to be non-dismissable, but also added logic to clear the notification when the battery status is back above the threshhold.
Also adds a progress bar to indicate battery percentage for a little flair.
This also adds some grouping to the growing variety of notifications as well that may help logically consolidate them in the drawer.
- Changes low battery notifications to be non-cancelable
- Cancel low battery notifications when battery level is no longer low.
- Add notification groups and improve notification settings.
- Add vibration to low battery notifications.
- Add progress bar to low battery notifications
(note: i artificially set the threshhold very high for testing)
> feat: Improve (battery) notification behavior

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/database/MeshLogRepository.kt
- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfigViewModel.kt
- Created a new `filteredNodeList` `StateFlow` in `UIState.kt` that filters out nodes marked as ignored.
- Updated `MapFragment.kt` to use `filteredNodeList` instead of `nodeList`, ensuring that ignored nodes are not displayed on the map.
fixes #1484 
https://github.com/user-attachments/assets/eab5b07a-9f65-49fe-8a64-421e5b0586fb
> fix #1484: Filter out ignored nodes from map

- app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
- app/src/main/res/values/strings.xml
This adds a bit more information to the marker popup for a node when tapped in the map view.
It comes up every so-often about the "time-ago" in the map being "incorrect" because it isn't immediately apparent that the duration displayed is actually the last received position packet, not the last received packet of any type. This attempts to help with that confusion by adding text showing both the node's last-heard time as well as the last-seen-position time.
Example:
> feat: Add a bit more info to the node marker popup

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/NetworkConfigItemList.kt
Only show UDP settings if the device has both Ethernet and WiFi.
> fix: Conditionally show UDP settings

- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
- app/src/main/java/com/geeksville/mesh/model/SortOption.kt
- app/src/main/res/values/strings.xml
PR to allow sorting favorite nodes to top of list.  This closes issue #1608.
> Allow sorting by favorite nodes for issue #1608

- renovate.json
Should consolidate Kotlin and KSP PRs from Renovate - which are dependent on each other
> chore(renovate): Update Renovate config to group Kotlin and KSP dependencies

- app/src/androidTest/java/com/geeksville/mesh/NodeInfoDaoTest.kt
- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
- app/src/main/java/com/geeksville/mesh/database/entity/NodeEntity.kt
- app/src/main/java/com/geeksville/mesh/model/Node.kt
- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
- Add a mismatchKey flag to Node and MessageTopBar to indicate a public key mismatch.
- Set the public key to a default error value (all zeros) when a node's public key changes.
- Display a warning in the MessageTopBar when a key mismatch is detected in PKC.
- Only clear all nodes when a different mynode number is present.
> fix: Handle node public key mismatch and show warning

- app/src/main/java/com/geeksville/mesh/ui/components/EnvironmentMetrics.kt
The barometric pressure line wasn't being scaled properly
> fix: use the appropriate min when scaling the barometric pressure data

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Previously the status string read `Nodes ( # / 100)` this updates the string to just show the raw node count `Nodes( # )` as a better representation, since a device's nodeDb may be smaller ( 80 in the case of nrf) or (200-250 for the cases of some esp32 devices with larger flash). 
resolves #1733
> fix: Remove nodeDb size from status string

- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfigViewModel.kt
Another stab at fixing pubkey mismatch detection, added local nodeDb clearing when resetting device nodeDb or factory reset.
> fix: clear local DB after reset

- app/src/main/java/com/geeksville/mesh/ui/components/BaseScaffold.kt
fixes #1603
fixes #1767
`BaseScaffold` is applying `imePadding()` to an internal `Box` on all screen-level Composables. This is evidently unnecessary with our setup and applies double keyboard padding for older devices.
On my Samsung A10e, Android 9:
|------|-----|
| <video src="https://github.com/user-attachments/assets/021e275c-0628-46b2-aa73-639ec5a4ed4c" width="300"></video> | <video src="https://github.com/user-attachments/assets/57737d25-4a3f-477c-be53-e1d7956e5a83" width="300"></video> |
Also tested on my Samsung S23 Ultra to verify this change didn't affect devices that didn't have this issue.
> fix: Remove imePadding modifier to internal scaffold box

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/res/values/strings.xml
The string "Connected: %1$s of %2$s online" in strings.xml has been changed to "Connected: %1$s online". The corresponding change has been made in MeshService.kt to use the updated string format, removing the reference to numNodes as it no longer makes sense when retaining the app node db between same-device connections.
> Update connected count string in strings.xml and MeshService.kt

- app/src/main/java/com/geeksville/mesh/ui/components/CopyIconButton.kt
- app/src/main/java/com/geeksville/mesh/ui/components/EditBase64Preference.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/SecurityConfigItemList.kt
- app/src/main/java/com/geeksville/mesh/util/ByteStringExtensions.kt
follows on from #1737  
Added capability to easily copy the public and private key fields in security config.
- Introduces `CopyIconButton` composable for copying text to the clipboard.
- Move `encodeToString` and `toByteString` extension functions to global utils for Base64 `ByteString` encoding/decoding.
- Implements usage of `CopyIconButton` for copying the Public Key and Private Key in SecurityConfigItemList screen.
- Implements usage of `readOnly` in EditBase64Preference for making it read only.
- Make Public and Private Key read only.
> feat: Add copy button to public/private key fields

- config/crowdin/crowdin.yml
Since moving the crowdin config yml to the `config/crowdin` folder, the base path needed to be updated to reflect the change in path.
> fix: correct base path in crowdin.yml

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/UserConfigItemList.kt
removes the automatic short name generation from long name - mentioned by @garthvh a few times, and a good idea.
https://github.com/meshtastic/Meshtastic-Android/issues/1810#issuecomment-2845130576
> refactor: Remove automatic short name generation from long name.

- .github/workflows/crowdin-download.yml
- .github/workflows/crowdin-upload.yml
This commit refactors the previous Crowdin Action workflow into two separate workflows: `crowdin-upload.yml` and `crowdin-download.yml`.
*   `crowdin-download.yml`: This workflow is now scheduled to run every Sunday at midnight, and can be manually triggered. It is responsible for downloading translations from Crowdin. It does not upload sources.
*   `crowdin-upload.yml`: This new workflow triggers on pushes to the `master` branch when the source `strings.xml` changes. It is responsible for uploading source files to Crowdin and can be manually triggered. It does not download translations.
> refactor(l10n): Split Crowdin Action into Upload and Download Workflows

- .github/renovate.json
Configure Renovate to auto-merge minor and patch updates, except for pre-1.0 versions. This leverages Renovate's existing functionality for common update types.
> chore(renovate): Auto-merge minor and patch updates

- app/src/main/java/com/geeksville/mesh/ui/Settings.kt
- app/src/main/res/values/strings.xml
I implemented #1567 by adding another text element with pre-selected default TCP port, which can be changed by the user. Showing default port is a good UX practice, otherwise it isn't clear which protocol is actually used (see messages in #1567 where user was confused by thinking the app uses HTTP API at port 80).
> fix #1567: Allow using a different TCP port than default 4403

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/DataStoreModule.kt
- app/src/main/java/com/geeksville/mesh/repository/location/LocationRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/Settings.kt
- gradle/libs.versions.toml
This commit refactors the "provide location" setting to use DataStore for persistence instead of SharedPreferences.
Key changes:
- Introduced `LocationRepository` to manage location-related data and preferences.
- Migrated the "provide location" preference to DataStore within `LocationRepository`.
- Updated `UIViewModel` to use `LocationRepository` for accessing and modifying the "provide location" setting.
- Modified `SettingsScreen` to reflect the changes in how "provide location" is handled.
- Ensured that changing the connected device resets the "provide location" setting to false.
- Ensured that re-connecting to the same device keeps the previous "provide location" setting
- Added necessary DataStore dependencies and module configurations.
> Refactor: Move "provide location" preference to DataStore

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/ContactSharing.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/components/SimpleAlertDialog.kt
- app/src/main/res/values/strings.xml
- config/detekt/detekt-baseline.xml
This commit enhances the shared contact import dialog by:
- Providing more detailed information when importing a known contact, including a warning about overwriting existing data and highlighting if the public key has changed.
- Displaying a comparison of old and new user data for known contacts.
- Showing all user fields for new contacts.
- Customizing the confirm and dismiss button text for clarity.
- Adding new string resources for the enhanced dialog messages.
- Exposing `unfilteredNodeList` in `UIState` to facilitate finding existing nodes during import.
> Refactor: Improve shared contact import dialog

- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/components/NodeFilterTextField.kt
- app/src/main/res/values/strings.xml
This commit removes the "include unmessageable" filter from the node list.
The functionality to filter out nodes based on their messageability status (e.g., repeaters, infrastructure nodes) has been removed from the UI and the underlying data layer.
The Direct Messaging visibility checks, and visual indication on the nodes are still in place.
> Refactor: Remove "include unmessageable" filter

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/ContactItem.kt
This commit updates the contact list to use the node's defined colors for the contact chip, providing a more personalized and visually distinct experience.
If the contact is a Channel, the default chip colors will be used.
> feat: Use node colors for contact chip

- app/src/main/java/com/geeksville/mesh/ui/components/NodeMenu.kt
Node menu show details action was being unintentionally hidden for old firmwares - this resolves that issue.
> fix: NodeMenu hiding details action

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt
- app/src/main/res/values/strings.xml
- config/detekt/detekt-baseline.xml
This commit introduces a "Request Metadata" action to the NodeDetail screen for remote devices. This allows users to request updated metadata from the device.
The `NodeDetailList` now accepts a generic `onAction` callback, which can handle both `Route` for navigation and `ServiceAction` for service-related actions.
The `DeviceActions` composable has been created to group device-specific actions like "Share Contact" and the new "Request Metadata".
The `MetricsViewModel` has been updated to handle `ServiceAction` and determine if the current node is the local device.
replaces #1517
> feat: Add request metadata action to NodeDetail

- .github/workflows/codeql.yml
The CodeQL workflow now:
- Checks out submodules recursively.
- Validates the Gradle wrapper.
- Sets up Gradle with caching.
- Builds debug artifacts using `./gradlew assembleDebug`.
> build: Add submodule checkout and Gradle setup to CodeQL workflow

- app/src/main/java/com/geeksville/mesh/repository/network/MQTTRepository.kt
The MQTT proxy client ID now includes "MeshtasticAndroidMqttProxy-" as a prefix to the existing ID generation logic (either the user's ID or a randomly generated client ID). This makes it easier to identify the source of MQTT messages in logs and monitoring tools.
> Generate more specific client ID for MQTT proxy

- app/src/main/java/com/geeksville/mesh/service/BootCompleteReceiver.kt
Potential fix for [https://github.com/meshtastic/Meshtastic-Android/security/code-scanning/30](https://github.com/meshtastic/Meshtastic-Android/security/code-scanning/30)
To fix the issue, the `onReceive` method should verify that the received intent's action matches the expected `Intent.ACTION_BOOT_COMPLETED`. If the action does not match, the method should return early without performing any operations. This ensures that the receiver only processes valid intents and mitigates the risk of malicious exploitation.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 30: Improper verification of intent by broadcast receiver

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeItem.kt
- app/src/main/java/com/geeksville/mesh/ui/NodeScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/components/NodeMenu.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageList.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/UserConfigItemList.kt
The node screen filter text field now fades in and out when scrolling.
The "Share My Info" button is now only visible when connected to a device.
Removed firmware version checks for QR code sharing.
Added toggle for Unmessageable, enabled if `hasIsUnmessageable()`
> feat: filter visibility, add unmessageable toggle

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- buildSrc/src/main/kotlin/Configs.kt
This commit moves the `MIN_DEVICE_VERSION` constant from `MeshService.kt` to the `Configs.kt` file within the `buildSrc` directory.
The value is now accessible via `BuildConfig.MIN_DEVICE_VERSION` and is set to "2.5.14".
This change centralizes build-related configurations and improves maintainability.
> refactor: Move MIN_DEVICE_VERSION to build config

- buildSrc/src/main/kotlin/Configs.kt
This commit disables Firebase Crashlytics by setting `USE_CRASHLYTICS` default to `false` in `Configs.kt`.
This fixes #1947
> fix(#1947): Disable Crashlytics for fdroid builds

- app/src/main/java/com/geeksville/mesh/ui/NodeItem.kt
This commit updates the `NodeItem` composable to correctly determine if a node is unmessageable.
Previously, it checked for firmware version "2.6.8" and the `isUnmessagable` user property.
Now, it prioritizes the new `hasIsUnmessagable()` flag on the user object. If this flag is not present, it falls back to checking the `isUnmessageableRole()` and the firmware version, defaulting to unmessageable if the firmware version is unavailable.
> refactor: use `is_unmessagable` flag

- app/src/main/java/com/geeksville/mesh/ui/components/LoraSignalIndicator.kt
The green color for the GOOD signal quality in the LoraSignalIndicator has been updated from `Color.Green` to a more specific green shade (`#30C047`) . Matches PKC lock coloring
saves @NomDeTom 's :eyes:
> fix: update LoraSignalIndicator GOOD color

- app/src/main/java/com/geeksville/mesh/repository/api/FirmwareReleaseLocalDataSource.kt
The `getLatestRelease` function in `FirmwareReleaseLocalDataSource.kt` now checks if the list of releases retrieved from the DAO is null or empty before attempting to find the maximum version. If it is null or empty, the function returns null. This prevents a potential crash if no releases are found for the given `releaseType`.
> Fix: Handle null or empty release list in `getLatestRelease`

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
This change refactors edge-to-edge display in the `MainActivity` by:
- Setting `WindowCompat.setDecorFitsSystemWindows(window, false)`.
- Wrapping the `MainScreen` composable in a `Box` with background and system bars padding.
- Applying `safeDrawingPadding()` to the `Scaffold` in `Main.kt`.
> fix: respect keyboard, edgeToEdge tweaks

- app/src/main/java/com/geeksville/mesh/navigation/NodeDetailGraph.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
This commit introduces a "Direct Message" button on the Node Detail screen, allowing users to initiate a direct message with the selected node.
Changes include:
- Added `navigateToMessages` lambda to `NodeDetailScreen` to handle navigation to the messages screen.
- Updated `NodeDetailGraph.kt` to pass the `navigateToMessages` lambda.
- Added a "Direct Message" `NodeActionButton` to the `NodeDetailScreen`.
- When the "Direct Message" button is clicked, it determines the appropriate channel (PKC or node's channel) and navigates to the messages screen with the user ID.
> feat: add Direct Message button to Node Detail screen

- app/src/main/java/com/geeksville/mesh/database/dao/FirmwareReleaseDao.kt
- app/src/main/java/com/geeksville/mesh/repository/api/FirmwareReleaseLocalDataSource.kt
The DAO methods `getAllReleases` and `getReleasesByType` already returned an empty `List<FirmwareReleaseEntity>` instead of `null`.
Fixes a build warning.
> refactor: FirmwareReleaseDao to return non-nullable lists

- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
Check if the node can receive DMs before showing the direct message button. This considers the `isUnmessageable` field and also checks `isUnmessageableRole()` for older firmware versions.
> fix: Only show DM button if node is messageable

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
- Update `createOpenMessageIntent` to use `FLAG_UPDATE_CURRENT` to ensure the correct `PendingIntent` is used.
- Pass `PendingIntent` to `commonBuilder` to simplify notification creation.
- Remove `unbindMeshService` and `onStop` override in `MainActivity` as service binding is handled by `ServiceRepository`.
> refactor: Update notification and service handling

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/AlertDialogs.kt
The version checking logic for app and firmware compatibility has been moved from `MainActivity.kt` to `Main.kt`.
This change ensures that:
- Version checks are performed within the Composable UI layer.
- Alerts for outdated app or firmware versions are now displayed using the `UIViewModel.showAlert` mechanism.
- On confirming these alerts, the device address is changed to "n", effectively disconnecting.
- The `UIState.kt` alert dialog now always dismisses itself on confirm, regardless of the `dismissable` flag.
https://github.com/user-attachments/assets/328814f9-24aa-4f07-ba23-f927493b04a5
> Refactor: Move version checks to Main.kt

- app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt
- app/src/main/java/com/geeksville/mesh/navigation/NodesGraph.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
This commit refactors the navigation for the node detail screen.
- Renames `NodeDetailGraph.kt` to `NodesGraph.kt`.
- Creates a new sealed class `NodesRoutes` to encapsulate routes related to nodes.
- Moves the `Nodes` route from the main `Route` sealed interface to `NodesRoutes`.
- Updates the main navigation graph to use the new `nodesGraph` and `NodesRoutes`.
- Adjusts how ViewModels are retrieved in `NodeDetailScreen` and related composables.
> Refactor node detail navigation

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/DataStoreModule.kt
- app/src/main/java/com/geeksville/mesh/repository/location/LocationRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
This commit fixes an issue where location sharing settings were not being applied correctly when switching between different Meshtastic devices. The "Provide location to mesh" setting is now saved per device, ensuring that your preference is respected for each connected node.
Additionally, the UI has been updated to reflect the actual status of location updates being sent to the mesh. The checkbox will now accurately show whether location data is being shared.
> Fix location sharing

- app/build.gradle
- app/src/main/java/com/geeksville/mesh/database/entity/FirmwareReleaseEntity.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/AlertDialogs.kt
- app/src/main/res/values/strings.xml
- buildSrc/src/main/kotlin/Configs.kt
This commit introduces a distinction between a recommended minimum firmware version and an absolute minimum firmware version.
- If the device firmware is below the *absolute minimum*, the user will be forced to update before proceeding.
- If the device firmware is below the *recommended minimum* but above the absolute minimum, the user will see a recommendation to update to the latest stable version to benefit from new features and fixes.
This change aims to improve user experience by providing clearer guidance on firmware updates and ensuring compatibility while allowing users with slightly older, but still functional, firmware to continue using the app.
> refactor: recommended and required firmware updates

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
This commit removes the clearing of the packet and mesh log databases when the device disconnects. The node database is still cleared.
> revert: do not clear databases on disconnect

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/node/components/NodeChip.kt
- app/src/main/java/com/geeksville/mesh/ui/node/components/NodeItem.kt
The `isUnmessageableRole` check previously included a firmware version comparison. This has been removed as it is no longer necessary.
Additionally, this commit:
- Fixes `UIState.isConnected` to correctly reflect any connected state.
- Updates `NodeChip` to use `Modifier` directly instead of `Modifier.Companion`.
- Enables "Done" key action on manual IP/Port input fields in the Connections screen to initiate connection.
> fix: connections ui and unmessageable logic

- app/src/main/java/com/geeksville/mesh/navigation/NodesGraph.kt
This change introduces a nested navigation graph, `NodeDetailGraph`, to encapsulate the `NodeDetailScreen` and its associated routes (Device Metrics, Node Map, etc.).
This improves the organization of the navigation structure by grouping related screens together. It also allows for a shared ViewModel scope for the `NodeDetailGraph`, simplifying ViewModel creation and management.
> Refactor: Nest NodeDetailScreen and related routes in a NodeDetailGraph

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
This change ensures that when `MainActivity` is launched via an intent (e.g., from a notification or shortcut), an existing instance of the activity is brought to the front instead of creating a new one. This improves the user experience by preventing multiple instances of the main activity from being created.
> Refactor: Use FLAG_ACTIVITY_SINGLE_TOP for MainActivity intents

- app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl
- app/src/main/java/com/geeksville/mesh/ApplicationModule.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/ReplyReceiver.kt
When a message list with unread messages is opened and scrolled to most recent item, an obsolete notification about unread messages in this channel/DM is now cancelled. Prior to this change notification had to be manually dismissed.
> fix: cancel new message notification when message is marked as read

- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
With this change, node list filter now recognizes partial or complete node number (decimal) and user id (hex, with optional exclamation mark prefix).
> feat: filter node list by user id or node number

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Redundantly clearDatabases() was called on all factory resets and nodeDB resets, even if they are remote nodes. I removed this.
Tested by clearing the node DB of the remote node.
Fixed  #2075
> Fixed nodeDB reset even on remote nodeDB reset

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
- app/src/main/java/com/geeksville/mesh/service/ServiceRepository.kt
This commit introduces support for client notifications.
- Added `clientNotification` StateFlow to `ServiceRepository` and `RadioConfigRepository` to manage client notifications.
- Implemented methods to set and clear client notifications in both repositories.
- Updated `MeshService` to handle `ClientNotification` by setting it in `RadioConfigRepository` and showing a service notification.
- Modified `UIState` to observe `clientNotification` and display an alert dialog when a notification is received.
- Added a new notification channel and methods to show and clear client notifications in `MeshServiceNotifications`.
> refactor: Client Notification Support

- app/build.gradle.kts
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- gradle/libs.versions.toml
refactor to [adaptive](https://developer.android.com/develop/ui/compose/layouts/adaptive) design.
This replaces the `Scaffold` and custom `BottomNavigation` in `MainScreen` with `NavigationSuiteScaffold` from the Material 3 adaptive library. This change allows the app's navigation to adapt to different screen sizes.
Dependencies for Material 3 adaptive components have been added to `gradle/libs.versions.toml` and `app/build.gradle.kts`.
The `MainScreen` composable now uses `NavigationSuiteScaffold` to display top-level destinations. The `MainAppBar` and `NavGraph` are now nested within a `Column` inside the `NavigationSuiteScaffold`.
The `BottomNavigation` composable has been removed as its functionality is now handled by `NavigationSuiteScaffold`.
In `MainActivity.kt`, the `Box` …
> feat: adaptive nav

- app/src/main/java/com/geeksville/mesh/navigation/MapRoutes.kt
- app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapView.kt
Long-pressing a map node marker opens up a node detail screen.
Also factored out `MapRoutes` from `NavGraph` for consistency with other UI areas and for future map-related screens.
> feat: show node details by long-pressing a node marker on map

- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
- app/src/main/res/values/strings.xml
This change extends node detail screen by adding last known distance to the node and time of last position update from the node.
While last known distance is available on the nodes list, before this change it was not easily accessible from channel/DM screen.
> feat: show distance to the node on node details screen

- app/src/main/java/com/geeksville/mesh/ui/node/components/NodeKeyStatusIcon.kt
Added a copy button to the Public key lock icon - #2093 
Tested and working on HW.
> add copy button to pbk for node status icon

- app/src/main/java/com/geeksville/mesh/navigation/NodesRoutes.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
**Problem:**
When removing a node from the node detail screen, the app would hang instead of navigating back to the previous screen. The "More details" action was also affected by the initial fix attempt.
**Solution:**
Navigate immediately after the remove action is confirmed, rather than trying to detect when the node becomes null in the state. This provides immediate user feedback and avoids interfering with other navigation actions.
**Changes:**
- Added `onNavigateUp` callback to `NodeDetailScreen`
- Navigate immediately after `NodeMenuAction.Remove` is processed
- Removed problematic `LaunchedEffect` that was triggering on any null state
**Testing:**
- Node removal now properly navigates back to previous screen
- "More details" and other navigation actions work correctly
- No hanging …
> Fix node removal hang by adding navigation callback

- app/src/main/java/com/geeksville/mesh/ui/message/MessageList.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/Reaction.kt
This commit refactors the `MessageItem` composable to improve its layout and how it displays message reactions.
fixes #2125
Key changes:
- `MessageItem` now uses a `Column` as its root element instead of a `Row` for better control over vertical arrangement.
- The `ReactionRow` is now directly embedded within the `MessageItem` with improved user experience.
- The message bubble color for messages from other users is now derived from the node's color with an alpha transparency.
- The sender's name and ID are displayed above the message content for non-local messages.
- The `hopsAway` and SNR/RSSI information for non-local messages is now displayed more consistently.
- Minor padding and spacing adjustments have been made for a cleaner appearance. …
> Refactor: Improve MessageItem layout and display of reactions

- app/src/main/java/com/geeksville/mesh/ui/map/MapViewWithLifecycle.kt
Removes redundant onDetatch in favor of lifecycle handling.
Fixes NPE crash when navigating into and away from the map quickly.
fixes #2094
> fix(#2094): remove redundant mapView.onDetach() call

- app/src/main/java/com/geeksville/mesh/DataPacket.kt
- app/src/main/java/com/geeksville/mesh/database/entity/Packet.kt
- app/src/main/java/com/geeksville/mesh/model/Message.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
- app/src/main/java/com/geeksville/mesh/ui/message/MessageList.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/Reaction.kt
This commit introduces the ability to reply to messages within the application.
Key changes include:
- **Data Model Updates:**
- `DataPacket` now includes an optional `replyId` field to link replies to original messages.
- `Packet` entity in the database is updated to store `replyId`, defaulting to -1.
- `Message` model now includes an optional `replyId`.
- **UI Enhancements:**
- **Message Input:** - A visual indicator ("Replying to...") appears above the text input when a reply is being composed. - Users can cancel the reply using a close button.
- **Message Display:**
- Replies now display a quoted snippet of the original message.
- The original message snippet is clickable, navigating the user to the original message in the chat history. - A "Reply" icon button is added to the message …
> feat: Implement message reply functionality

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/SecurityConfigItemList.kt
- app/src/main/res/values/strings.xml
This commit introduces the ability to export public and private keys to a JSON file.
Changes:
- Added "Export Keys" button and confirmation dialog to the Security settings screen.
- Implemented `exportSecurityConfig` and `writeSecurityKeysJsonToUri` in `RadioConfigViewModel` to handle the export process.
- Keys are Base64 encoded and saved in a JSON file with a timestamp.
- Added new string resources for the export feature.
> feat: Add key export functionality

- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
Fixes an issue where the message text field would sometimes not clear after sending a message, leaving the old text visible even though the message was successfully sent.
**Problem:** Text clearing logic was happening inside the TextInput composable while state changes (like clearing reply state) were happening in the parent composable, creating a timing issue during recomposition.
**Solution:** Moved the text clearing to happen at the parent level after all message sending and state updates are complete.
**Testing:** Verified text field clears properly when sending both regular messages and replies, using the send button and the enter key.  Tested on a TCL T768S (Android 11)
Closes #2150
> Fix text input not clearing after sending message

- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
> fix (#2172): replace string template for `Hops Away:`

- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
- app/src/main/res/values/strings.xml
Updated the string resource for "hops away" to use a template for better localization support. Modified `MessageItem.kt` to utilize the new string template.
@lkosson 🙃 
https://github.com/meshtastic/Meshtastic-Android/issues/2172#issuecomment-2991637066
> fix: Use string template for hops away

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/SecurityConfigItemList.kt
- app/src/main/res/values/strings.xml
clears publick key when private key is edited or regenerated, displays original public key if original private key is reset.
Additional messaging added for the dialog to explain that the changed key node must be `Removed` and key exchange must happen again before interaction.
> fix: clear public key when private key edited

- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/Reaction.kt
- app/src/main/java/com/geeksville/mesh/ui/node/components/NodeChip.kt
This commit refactors the message item actions and reactions:
- Moves the reaction and reply buttons to a new `MessageActions` composable.
- Makes the reactions list visible only when there are reactions.
- Adjusts padding and sizing for a cleaner look.
> Refactor message item actions and reactions

- app/src/main/java/com/geeksville/mesh/ui/node/components/NodeChip.kt
Change #2191 caused node chips with hyphen or space **and** full-width letters (`W`, `M` etc) to be displayed in two lines (see 2nd message in the screenshot). This change reverts `minWidth` from `48dp` back to `72dp` and also adds `maxLines = 1` as a safeguard when someone puts line breaks or other exotic unicode characters in `shortName`.
> fix: unintended line break in node chip

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfig.kt
- app/src/main/res/values/strings.xml
This commit introduces two changes to the app bar:
- A "(Remote)" indicator is now displayed next to the node name in the title when viewing the radio configuration of a remote node.
- A chip representing the local device node is now displayed in the app bar actions. This chip provides quick access to node details and sharing options.
Additionally, the `setTitle` function in `UIState.kt` is now launched within a `viewModelScope` to ensure it runs on the main thread.
> refactor: Add remote node indicator and node chip to app bar

- mesh_service_example/src/main/java/com/meshtastic/android/meshserviceexample/MainActivity.java
- mesh_service_example/src/main/res/layout/activity_main.xml
- mesh_service_example/src/main/res/values/strings.xml
This commit introduces a "Send Hello Message" button to the main activity of the MeshServiceExample app. When clicked, this button sends a broadcast text message "Hello from MeshServiceExample" to the mesh network.
thanks again @niccellular !
> feat: Add send message service example

- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
Resolves issue where message text field wouldn't clear after sending messages.
**Root Cause:** rememberSaveable without key caused state interference between conversations and recompositions.
**Solution:** Added contactKey as rememberSaveable key + centralized text clearing in MessageScreen callback for single responsibility and reliable behavior.
Tested on a TCL T768S
First attempt was #2161 in but these changes are necessary as well
Related issues: #1474, #2150
> fix: message input clearing with proper state management (#1474 & #2150)

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Not sure if it belongs here, but worth a shot.
[Forked firmware](https://github.com/musznik/firmware) popular around here broadcasts telemetry with `hasLocalStats` over the radio for some reason, randomly replacing local stats in notification with the ones received from remote node. It shouldn't do it, but it does, breaking stats for everyone around. Not much can be done about operators running this firmware version, and official firmware never produces such messages, but such packets could be ignored without any harm.
> fix: ignore non-local localStats telemetry

- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
This introduces a feature that displays the count of online and total nodes in the application's title bar.
The changes include:
- Adding `onlineNodeCount` and `totalNodeCount` StateFlows to `UIState.kt` to observe these values from the `NodeRepository`.
- Modifying `Main.kt` to collect these counts and update the `TopAppBar` title to show "App Name (online/total)" when viewing the nodes list.
- Adding `onlineNodeCount` and `totalNodeCount` Flows to `NodeRepository.kt` to provide the counts of online and total nodes from the database.
replaces #1958
> feat: show online and total node count in the title bar

- app/src/main/java/com/geeksville/mesh/ui/map/components/MapButton.kt
Removes the explicit `CircleShape` from the `MapButton` Composable, allowing it to use the default shape provided by `FloatingActionButton`.
> Refactor: Use default FAB shape for MapButton

- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/res/values/strings.xml
Moves the online/total node count from the title to the subtitle of the `MainAppBar` when the current destination is the Nodes screen. This change utilizes the `subtitle` parameter of the `TopAppBar` and introduces a new string resource `node_count_template` for formatting. 
Additionally, it opts into `ExperimentalMaterial3ExpressiveApi`.
> Refactor node count display in MainAppBar

- app/src/main/java/com/geeksville/mesh/ui/common/components/AutoLinkText.kt
- app/src/main/java/com/geeksville/mesh/ui/message/MessageList.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/node/components/NodeItem.kt
- Standardize item animations in `NodeScreen` and `MessageList` using `Modifier.animateItem()`.
- Apply consistent card colors in `NodeItem` and `MessageItem` based on node colors.
- Ensure `AutoLinkText` respects the provided text color.
- Refactor `MessageItem` to use `CardColors` for `ReplyingTo` component.
> Refactor: Improve UI consistency and animations

- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
This commit refactors the message input field in the Message screen to use the new `BasicTextField2` from Jetpack Compose Foundation.
Provides cleaner handling for clearing state.
The key changes include:
- Replacing `MutableState<TextFieldValue>` with `TextFieldState`.
- Using `rememberTextFieldState` to manage the input field's state.
- Updating text manipulation from `messageInput.value = TextFieldValue(...)` to `messageInput.setTextAndPlaceCursorAtEnd(...)` and `messageInput.clearText()`.
- Simplifying keyboard event handling for sending messages.
- Making the `TextInput` composable single-line and updating the UI for character count and error states.
- Setting `fillMaxSize()` on the `Scaffold` to ensure it occupies the entire screen.
supercedes #2229 
fixes #1474
> Refactor message input to use BasicTextField2

- app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/BLEDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/DeviceListItem.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/NetworkDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/UsbDevices.kt
- app/src/main/res/values/strings.xml
This commit refactors the Connections screen by:
- Adding support for Mock and Disconnect device types in `BTScanModel.kt`.
- Introducing new string resources for "Disconnect", and messages for when no Bluetooth, Network, or USB devices are found.
- Creating new Composable functions for displaying Network, BLE, USB devices, and a generic DeviceListItem.
- Updating the `Connections.kt` to use these new components, replacing the Floating Action Button with a SegmentedButtonRow for device type selection, and adding a disconnect button.
> Refactor Connections screen and add new strings

- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
- app/src/main/java/com/geeksville/mesh/ui/message/MessageList.kt
This resolves an issue where unread messages were not being marked as read when conversations were opened for the first time. Findings from another PR (#2235) helped identify the root cause - the UpdateUnreadCount function was receiving an empty messages list due to Compose state synchronization issues.
**Root Cause Analysis:**
The issue was traced to a Compose state synchronization problem where UpdateUnreadCount in MessageList was seeing an empty messages list, causing the unreadIndex to remain at -1 and preventing the onUnreadChanged callback from being triggered. The messages were properly populated at the MessageScreen level but weren't being passed correctly to the UpdateUnreadCount composable.
**Solution:**
- Restructured the LaunchedEffect to always observe scroll changes, …
> fix: unread message count not updating when opening conversations

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/map/components/EditWaypointDialog.kt
The iOS app sends non-expiring waypoints as expire=0; we will now treat those as never expiring and always show them. Additionally, the Date and Time formatted strings sometimes did not display, so we now initialize them instead of using onChange.
> Fix waypoints

- app/src/main/java/com/geeksville/mesh/repository/network/ConnectivityManager.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
Fixes deprecated `allNetworks` access
The `ConnectivityManager.networkAvailable()` flow now more accurately reflects network availability by:
- Tracking individual network connections using `onAvailable` and `onLost` callbacks.
- Responding to network capability changes via `onCapabilitiesChanged`.
- Emitting updates only when the set of active networks changes or their capabilities change.
This provides a more robust and responsive way to determine if a network connection is currently available.
> Refactor: Improve network availability observation

- .github/workflows/android.yml
- .github/workflows/release.yml
- app/build.gradle.kts
- app/src/main/java/com/geeksville/mesh/database/dao/PacketDao.kt
- build.gradle.kts
- buildSrc/src/main/kotlin/Configs.kt
- gradle.properties
- mesh_service_example/build.gradle.kts
- network/build.gradle.kts
This commit introduces several improvements to the GitHub release workflow and the project's build configuration:
**GitHub Release Workflow (`.github/workflows/release.yml`):**
*   **Workflow Dispatch Inputs:**
*   Added `branch` input to specify the branch for the build.
*   Added `create_github_release` boolean input to control whether a GitHub release is created and assets are uploaded.
*   **Job Structure:**
*   Separated build steps into distinct jobs: `prepare-release-info`, `build-fdroid`, `build-google`, and `create-github-release`.
*   `prepare-release-info` extracts `versionCode` and `versionName` to be used by other jobs.
*   Build jobs (`build-fdroid`, `build-google`) now depend on `prepare-release-info`.
*   `create-github-release` job now depends on all build jobs and only …
> Refactor: Improve GitHub release workflow and build configuration

- app/build.gradle.kts
- mesh_service_example/build.gradle.kts
- network/build.gradle.kts
- settings.gradle.kts
- Implement JVM toolchain (JDK 21) across all modules (app, network, mesh_service_example) for consistent build environment.
- Add Foojay toolchain resolver to settings.gradle.kts for automatic JDK provisioning.
- Disable Crashlytics tasks for F-Droid builds in app/build.gradle.kts to avoid including proprietary libraries.
- Remove redundant compileOptions for Java version and JvmTarget settings as they are now handled by the toolchain.
- Clean up commented-out license headers in mesh_service_example/build.gradle.kts.
> Refactor: Use JVM toolchain and disable Crashlytics for F-Droid

- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/NetworkDevices.kt
This commit refactors the network device selection UI and logic by:
- **Removing the `RadioButton`** for manual IP address entry and **replacing it with an `IconButton`** with a `WifiFind` icon. This provides a more intuitive way to add a device by IP.
- **Improving the layout** of the manual IP address and port input fields using `Row` with `weight` modifiers for better responsiveness.
- **Adjusting the `KeyboardType`** for IP address and port input to `KeyboardType.Decimal` for better usability.
- **Updating the logic for determining the selected device type.** The `selectedDeviceType` now dynamically updates based on the currently selected device's address prefix, falling back to the last selected type if disconnected.
- **Introducing a `DeviceType.fromAddress()` helper function** to …
> Refactor: Improve network device selection UI and logic

- .github/workflows/android.yml
- app/src/main/java/com/geeksville/mesh/ui/debug/DebugFilters.kt
- reduce timeouts (still ~3x typical) 
- nest the || true that is there to stop the dependence on crashpad existing, so it doesn't override the result. 
To verify: 
Look at the last 2 workflows on the branch - only change is whether they have an intentional failure or not.
> 2269 - CI testing not failing correctly

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt
This commit introduces a change to clear all notifications when a user changes devices. This is achieved by calling `clearNotifications()` in `MeshService` which in turn calls a new `clearNotifications()` function in `MeshServiceNotifications` that uses `notificationManager.cancelAll()`.
Prevents Tom from talking to himself (via mesh).
> fix: Clear notifications on device switch

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/UserConfigItemList.kt
Allow unmessageable changes when `is_unmessagable` has not been set but is available (fw 2.6.9+).
@b8b8
> Fix unmessageable toggle

- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
- app/src/main/java/com/geeksville/mesh/ui/message/MessageList.kt
- app/src/main/res/values/strings.xml
This commit introduces a "scroll to bottom" floating action button in the message list view.
The button appears when the user can scroll backward (i.e., when not at the very bottom of the list). Clicking the button smoothly animates the list to the newest message.
The `LazyListState` is now initialized in the `MessageScreen` and passed down to `MessageList` to enable this functionality. A new string resource `scroll_to_bottom` has also been added.
https://github.com/user-attachments/assets/3128ffba-5bf9-427f-811b-78a773499ed4
> feat(#2080): Add scroll to bottom button in message list

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/navigation/ConnectionsRoutes.kt
- app/src/main/java/com/geeksville/mesh/navigation/ContactsRoutes.kt
- app/src/main/java/com/geeksville/mesh/navigation/MapRoutes.kt
- app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt
- app/src/main/java/com/geeksville/mesh/navigation/NodesRoutes.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
This commit removes the `Route.Dispatcher` and instead sets the `startDestination` of the `NavHost` conditionally based on the connection status.
It also updates various navigation calls to use `NodesRoutes.NodeDetailGraph` instead of `NodesRoutes.NodeDetail` where appropriate, ensuring correct navigation to node details.
> Refactor: Remove dispatcher and use conditional start destination

- mesh_service_example/README.md
adds `mesh_service_example\README.md`
> chore (repo): Add README.md for mesh_service_example

- app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
This PR refactors the device address detection logic in `RadioInterfaceService.kt` by replacing the broader `isMockInterface()` check with a more specific `BuildUtils.isEmulator` check. The change makes the mock interface address fallback more precise by targeting only emulator environments rather than all debug builds and test lab scenarios.
**Key Changes:**
- Added import for `BuildUtils`
- Replaced `isMockInterface()` method call with `BuildUtils.isEmulator` in `getDeviceAddress()`
- Narrowed the scope of when mock interface address is used as fallback
The mock interface was being auto loaded on physical devices which was making troubleshooting connection & state issues difficult on physical devices.
Demo mode is still available in the Serial tab if needed on a physical device.
Tested …
> Improved detection of emulator environments

- .github/workflows/merge-queue.yml
- .github/workflows/pull-request.yml
This commit introduces separate GitHub Actions workflows for Pull Requests (PR) and the Merge Queue.
The key changes are:
*   **`merge-queue.yml` (renamed from `android.yml`):**
*   Triggered only on `merge_group` events.
*   Removed `push` and `pull_request` triggers.
*   Concurrency group updated to `build-mq-${{ github.ref }}`.
*   Removed artifact uploads (debug APK, build reports, test reports) as these are not needed for merge queue checks.
*   Added Gradle and Android build caching steps to potentially speed up builds.
*   **`pull-request.yml` (new file):**
*   Triggered only on `pull_request` events targeting the `main` branch.
*   Concurrency group set to `build-pr-${{ github.ref }}`.
*   Includes steps to upload debug APK, build reports, and test reports with a retention period …
> ci: split workflows for PR and merge queue

- config/crowdin/crowdin.yml
- Use `update_as_unapproved` for `update_option`
- Set `escape_quotes` to 2
- Specify `android` as `type`
- Remove deprecated `update_strings`
closes #2344
> Update Crowdin config

- app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/BLEDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/DeviceListItem.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/NetworkDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/UsbDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
- app/src/main/java/com/geeksville/mesh/ui/node/components/NodeStatusIcons.kt
This commit refactors the UI to provide a clearer and more consistent indication of the connection state.
Key changes:
- **DeviceListItem:**
- Now accepts `connectionState` to dynamically update its appearance.
- Selected "Disconnect" items now have an error container color.
- Selected connected devices show a green "CloudDone" icon.
- Selected disconnected or connecting devices show appropriate icons and colors.
- **BLEDevices, UsbDevices, NetworkDevices:**
- Pass `connectionState` to `DeviceListItem`.
- "Disconnect" option is now shown in each device type list instead of being a separate button.
- Improved logic for displaying "no devices found" messages.
- **Connections Screen:**
- Removed the dedicated "Disconnect" button. Disconnection is now handled by selecting the "Disconnect" …
> Refactor: Improve connection state display in UI

- gradle/wrapper/gradle-wrapper.properties
The `distributionUrl` in `gradle-wrapper.properties` has been updated to point to Gradle version 8.14.3.
> chore (deps): Update Gradle wrapper to 8.14.3

- .github/workflows/pull-request.yml
- It shouldn't touch code, so it should be safe to skip the tests on every update of an MR. 
- It will still get tested overall in the merge queue, but it'll save repeated runs.
> skip test and lint on scheduled-updates

- .github/workflows/pull-request.yml
Reverts meshtastic/Meshtastic-Android#2367
we actually need this to run to pass the required checks to go into the merge queue
> Revert "skip test and lint on scheduled-updates"

- .github/workflows/release.yml
- .github/workflows/reusable-android-build.yml
- app/build.gradle.kts
- buildSrc/src/main/kotlin/Configs.kt
This commit introduces an automated `versionCode` generation strategy based on repository commit count for Android builds in the CI/CD pipeline.
Key changes:
- Updated GitHub Actions workflows (`release.yml`, `reusable-android-build.yml`) to:
- Set `fetch-depth: 0` for `actions/checkout` to get the full commit history.
- Add a step to calculate `versionCode` by adding an offset (30630) to the total Git commit count (`git rev-list --count HEAD`). This ensures `versionCode` always increases and is above previous manual values.
- Pass the calculated `VERSION_CODE` as an environment variable to Gradle build steps.
- Modified `app/build.gradle.kts` to read `versionCode` from the `VERSION_CODE` environment variable, falling back to 1 if not set.
This change aims to simplify the release process …
> chore(ci): Decouple versioncode

- .github/workflows/reusable-android-build.yml
- .github/workflows/reusable-android-test.yml
This commit updates the Gradle cache keys in the reusable Android build and test workflows to be more specific and include `libs.versions.toml` and `.kts` files.
It also modifies the execution of Gradle tasks in the build workflow to explicitly target the `:app` module for `detekt`, `lint`, `assemble`, and `test` tasks.
> Refactor: Update Gradle cache keys and task execution in CI

- .github/workflows/merge-queue.yml
This commit adds a new job `scheduled_updates` to the merge queue workflow. This job is configured to always pass, satisfying a required check for the merge queue that is primarily intended for PR entry.
> Fix: Satisfy merge queue check for scheduled updates

- app/build.gradle.kts
- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
- app/src/main/res/values/strings.xml
- gradle/libs.versions.toml
This commit introduces the ability to view detailed information about firmware versions in the Node Detail screen.
Users can now:
- See the installed firmware version and its status (e.g., outdated, stable, alpha).
- View the latest stable and alpha firmware versions available.
- Tap on a firmware version to open a bottom sheet displaying its release notes (rendered from Markdown) and links to view the release page or download the firmware ZIP.
Key changes include:
- Added new string resources for firmware details.
- Integrated a Markdown rendering library.
- Refactored `NodeDetail.kt` to:
- Separate concerns into smaller, more manageable Composables.
- Introduce a `NodeDetailAction` sealed interface for better event handling.
- Implement a modal bottom sheet to display firmware release …
> feat(nodes): display firmware details and release notes

- app/src/main/java/com/geeksville/mesh/model/Node.kt
The soil temperature display was incorrectly showing the air temperature when the temperature unit was set to Fahrenheit. This commit corrects the logic to display the actual soil temperature in Fahrenheit.
> Fix: Soil temperature shows air temperature when Fahrenheit is selected

- app/build.gradle.kts
Allows Composable functions to start with a lowercase letter, aligning with Jetpack Compose conventions.
> chore(ktlint): ignore function naming for composables

- app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt
This pull request adds support for a new regional frequency option in the `RegionInfo` enum class, for Brazil's 902 MHz band.
* [`app/src/main/java/com/geeksville/mesh/model/ChannelOption.kt`](diffhunk://#diff-f517dfd94646a02d56f6d5eb7776697f184eee0f67a8447be9c0396503542e7cL293-R300): Added a new entry `BR_902` to the `RegionInfo` enum, representing the Brazil 902 MHz frequency range (902.0 MHz to 907.5 MHz) with `wideLora` set to `false`. 
* This change references https://github.com/meshtastic/firmware/pull/7399
> Add new region: BR_902 "Brazil 902Mhz"

- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
The Floating Action Button (FAB) for scrolling to the bottom of the message list was previously shown when `listState.canScrollForward` was true. This has been corrected to use `listState.canScrollBackward`, which accurately reflects the ability to scroll towards the newest messages (index 0) in a reversed layout.
fixes #2496
> fix(ui): correct scroll direction for FAB visibility in message list

- app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/DataStoreModule.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/recentaddresses/RecentAddress.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/recentaddresses/RecentAddressesRepository.kt
To address some crash reports, this commit refactors the `BTScanModel` to use the more robust Jetpack DataStore for managing recent IP addresses, replacing the previous SharedPreferences implementation.
- Introduced `RecentAddressesRepository` to handle the storage and retrieval of recent IP addresses using DataStore.
- Created a `RecentAddress` data class to represent a recent IP address entry.
- Updated `BTScanModel` to use `RecentAddressesRepository` for managing recent IP addresses.
- Added a DataStore migration from SharedPreferences to ensure existing recent IP addresses are preserved.
- Added `providePreferencesDataStore` and `provideRecentAddressesRepository` to `DataStoreModule`.
> refactor(BTScanModel): migrate recent IP addresses to DataStore

- .github/workflows/release.yml
- .github/workflows/reusable-android-build.yml
- .github/workflows/reusable-android-test.yml
- settings.gradle.kts
Refactor GitHub Actions workflows to streamline Gradle and JDK setup.
- Consolidate JDK setup into the checkout action.
- Replace manual Gradle caching with the `gradle/actions/setup-gradle` action for improved caching and build scan integration.
- Remove redundant Gradle wrapper validation in `reusable-android-build.yml` as it's covered by `setup-gradle`.
- Remove AVD caching in `reusable-android-test.yml` as it's often ineffective.
> ci: configure Gradle actions and JDK setup

- app/src/main/java/com/geeksville/mesh/ui/common/theme/CustomColors.kt
- app/src/main/java/com/geeksville/mesh/ui/message/components/MessageItem.kt
This pull request introduces improvements to the `MessageItem` component in the `MessageItem.kt` file, adding a visual border for messages that contain the BEL character.
Im trying to solve https://github.com/meshtastic/Meshtastic-Android/issues/2518
* Added a conditional border to messages containing the BEL character (`\u0007`). The border is styled with a red color and medium shape to visually distinguish such messages.
* Added the `border` import to support the new visual enhancement.
> feat(MessageItem): add bell emoji to message if it contains BEL char

- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
Shows an icon corresponding to the firmware edition in the node detail view. Vanilla firmware is represented by an ice cream icon, while other editions use a fork icon.
> feat(ui): display firmware edition icon

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/navigation/ContactsRoutes.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapView.kt
- app/src/main/java/com/geeksville/mesh/ui/message/Message.kt
This commit introduces an overflow menu in the message screen's top app bar. This menu provides options to toggle the visibility of the quick chat panel and to navigate to the quick chat options screen.
- Added a `navigateToQuickChatOptions` parameter to `MessageScreen` and `contactsGraph` to handle navigation to the quick chat options.
- Created a `MessageTopBarActions` composable to encapsulate the actions in the top app bar, including the new overflow menu.
- Created an `OverFlowMenu` composable to display the menu items.
- Updated icons for quick chat actions.
- Visibility state is saved as a shared preference to persist.
This tucks everything away by default, but makes it accessible to those who actually use the Quick Chat feature. …
> feat(message): add overflow menu to message screen

- app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/BLEDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/DeviceListItem.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/NetworkDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/UsbDevices.kt
- app/src/main/res/values/strings.xml
This commit refactors the device list management in the connections screen and related components. It introduces a `DeviceListEntry` sealed class to represent different types of devices (BLE, USB, TCP, Disconnect, Mock) in a more type-safe and idiomatic Kotlin way.
This change improves code readability and robustness by enabling exhaustive `when` expressions and reducing the reliance on boolean flags (e.g., `isBLE`, `isUSB`).
The `BTScanModel` has been updated to use these sealed classes and provides separate StateFlows for each device type (`bleDevicesForUi`, `tcpDevicesForUi`, `usbDevicesForUi`). This simplifies the UI logic for displaying and filtering devices.
The "Warning Not Paired" message on the connections screen will now only be shown once per app installation if no BLE devices …
> refactor(connections)!: Use sealed class for device list entries

- app/src/main/java/com/geeksville/mesh/ui/metrics/HostMetricsLog.kt
- app/src/main/res/values/strings.xml
The load average progress indicators were dividing by 100.0f instead of 10000.0f, causing them to display incorrectly. This commit corrects the calculation.
Additionally, the display of the `userString` is displayed using a monospace font for better readability.
> fix(metrics): correct load progress calculation and user string

- app/src/main/java/com/geeksville/mesh/repository/radio/BluetoothInterface.kt
- app/src/main/java/com/geeksville/mesh/service/SafeBluetooth.kt
An attempt at making the bluetooth connection more reliable - this allows more time for recovery when buggy or intermittent.
**NEEDS TESTING**
This change introduces an exponential backoff mechanism for Bluetooth Low Energy (BLE) reconnection attempts. When a BLE connection drops or fails to establish, the system will now wait for an increasing amount of time before retrying. This approach aims to improve connection stability and reduce unnecessary strain on the BLE stack, especially in environments with intermittent connectivity.
The initial backoff delay is 1 second, and it doubles with each subsequent failed attempt, up to a maximum of 64 seconds (after 6 attempts). The reconnect attempt counter is reset upon a successful connection.
Additionally, this commit includes a refactoring of …
> refactor(bluetooth): exponential backoff for BLE reconnects

- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
- app/src/main/java/com/geeksville/mesh/database/entity/NodeEntity.kt
- app/src/main/java/com/geeksville/mesh/navigation/RadioConfigRoutes.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/CleanNodeDatabaseScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/CleanNodeDatabaseViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfig.kt
- app/src/main/res/values/strings.xml
This commit introduces a new screen for cleaning the node database. Users can specify criteria to delete nodes, such as nodes older than a certain number of days or unknown nodes. The list of nodes to be deleted updates dynamically as filter criteria change. A confirmation dialog is shown before deleting nodes.
The following changes are included:
- Added new string resources for the clean node database screen.
- Created `CleanNodeDatabaseScreen.kt` for the UI of the feature.
- Created `CleanNodeDatabaseViewModel.kt` to handle the logic for the screen.
- Added navigation to the new screen from the radio configuration settings.
- Extended `NodeEntity` with a `toModel()` function.
- Updated `NodeRepository` to include functions for fetching nodes based on age and unknown status, and for …
> feat(radioconfig): add clean node database screen

- app/src/main/java/com/geeksville/mesh/database/MeshLogRepository.kt
- handle both env and dev metrics coming in in separate telemetry messages
Closes #2604 
Introduced in #2556
My concern with that one was vindicated. 
Need to keep an eye on any other metrics that may fall through the same cracks. 
And we need to get some UI testing up.
> Fix regression of deviceMetrics

- CONTRIBUTING.md
Adds spotless doco to `CONTRIBUTORS.md`
Clarify that spotless is used for automated code formatting and provide commands for applying formatting and installing a pre-push Git hook.
> docs: add information about spotless for code formatting

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Add Types to new issues, 
GH Issues now have types., and labels. 
PR's only have labels.
Types are mutually exclusive, and organisation managed.
I don't know if they'll prove useful, and we can reduce our labels to MRs + escalation / clarity, or whether they'll offer no value
> Add Types to the templates

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
This commit introduces handling for two new packet types received from the radio: `DeviceUIConfig` and `FileInfo` - mitigating the "Unexpected FromRadio variant" error in the logs
When these packets are received:
- They are logged with a debug message.
- A `MeshLog` entry is created with the relevant information.
- The `MeshLog` entry is inserted into the database.
chatted w/ garth on vc, tl;dr - no we don't need to do anything special w/ these right now.
we could leverage the FileInfo to pull the rangetest csv file directly from the device. (currently generating our own from inapp debug logs)
> feat(service): handle DeviceUIConfig and FileInfo packets

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/labeler.yml
closes #2650
- Move the code folding in the bug form behind comments 
-  we can still edit and uncomment it for ones where it's useful (ie. big logs) 
- Make the catchall on the labeler only function when it's the first word, to stop double labeling a lot of things. 
_We could enforce branch rules:  `[ fix/#[0-9]**,  feat/#[0-9]**, repo/#[0-9]** ]` would be my preference, but I'm happy with whatever._
> #2650 - make the catch all on the labeler less generic

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/PositionConfigItemList.kt
- app/src/main/res/values/strings.xml
Adds a button to the Position Configuration screen to allow the user to populate the latitude, longitude, and altitude fields using the phone's current location.
This requires location permissions. If permissions are not granted, pressing the button will request them.
https://github.com/user-attachments/assets/f5214dc0-4145-4f93-baaa-f151e023e9c8
> feat(radioconfig): use current location for position config

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/database/dao/NodeInfoDao.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/datastore/RadioConfigRepository.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
- app/src/main/java/com/geeksville/mesh/service/ConnectionRouter.kt
- app/src/main/java/com/geeksville/mesh/service/ConnectionState.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceBroadcasts.kt
- app/src/main/java/com/geeksville/mesh/service/MeshServiceStarter.kt
- app/src/main/java/com/geeksville/mesh/service/ServiceRepository.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/BLEDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/DeviceListItem.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/NetworkDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/UsbDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/radioconfig/RadioConfigViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/sharing/Channel.kt
- app/src/main/res/values/strings.xml
This pull request focuses on a significant refactoring of the app's connection handling logic to improve stability and maintainability.
The key changes are:
- A new ConnectionRouter class has been introduced to centralize and manage the connection to the Meshtastic device. This class is now responsible for handling all connection state transitions, including connecting, disconnecting, and device sleep states.
- The MeshService has been simplified, with all connection management responsibilities delegated to the new ConnectionRouter.
- The underlying code for connection state has been moved to a dedicated ConnectionState enum, and a new CONNECTING state has been added for more granular status updates.
Various parts of the UI and data repositories have been updated to use this new, more …
> feat(service)!: refactor configuration, nodedb, and connection states

- app/src/google/java/com/geeksville/mesh/android/GeeksvilleApplication.kt
- gradle/libs.versions.toml
This commit adds the `dd-sdk-android-session-replay` and `dd-sdk-android-session-replay-compose` libraries to the project's dependencies. These libraries provide session replay capabilities for Android applications, allowing developers to record and replay user sessions for debugging and analysis purposes.
- Added `dd-sdk-android-session-replay` and `dd-sdk-android-session-replay-compose` to the `[libraries]` section of `gradle/libs.versions.toml`.
- Added `dd-sdk-android-session-replay` and `dd-sdk-android-session-replay-compose` to the `datadog` bundle in the `[bundles]` section of `gradle/libs.versions.toml`.
> feat(deps): add Datadog session replay libraries

- app/src/main/java/com/geeksville/mesh/ui/radioconfig/components/PowerConfigItemList.kt
This commit removes the "Light Sleep Duration" setting from the Power configuration screen in the radio config. This setting was previously available but is now managed by the firmware.
> feat(radioconfig): Remove light sleep duration setting

- .github/workflows/dependency-submission.yml
Just adding the main repository check to dependency graph submission workflow, so that it won't run on forks by default
> chore: Only run dependency submission workflow for the main repository

- .github/workflows/release.yml
This commit adds the `GOOGLE_MAPS_API_KEY` secret to the release workflow. This key is necessary for building the release version of the app that includes Google Maps functionality.
> ci(release): add GOOGLE_MAPS_API_KEY to release workflow

- .github/workflows/pull-request.yml
- crowdin.yml
This commit updates the `crowdin.yml` configuration file.
- Added labels for pull requests created by Crowdin: `automation` and `l10n`.
- Defined a commit message for translation updates: `Update translations from Crowdin` and adds the skip.
- modified the GitHub Actions workflow file `pull-request.yml`
to prevent the `build_and_detekt` and `androidTest` jobs from running
when changes are pushed to the `l10n_main` branch. This is in addition
to the existing condition that prevents these jobs from running on the
`scheduled-updates` branch
> chore: configure Crowdin integration

- crowdin.yml
Removes the custom commit message "\[skip ci] Update translations from Crowdin" from the Crowdin configuration. This allows Crowdin to use its default commit message for translation updates.
> chore(ci): remove custom commit message for Crowdin updates

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/MeshServiceClient.kt
I took a stab at decoupling the `MeshService` bind logic from `MainActivity`. This is a refactor, and no behavior change is expected. `MainActivity` is now injected with a `MeshServiceClient` that observes the Activity lifecycle and handles binding `MeshService`.
There is one minor issue that I called out in the comments. `MeshServiceClient` cannot be injected with the default `LifecycleOwner` binding for `@ActivityScoped` due to a global `LifecycleOwner` provided in `ApplicationModule` taking precedence. The current workaround is to inject `Activity` (not ideal) and cast to `LifecycleOwner`. Qualifying the provider in `ApplicationModule` solves this issue, but would add a ton of scope to this PR.
> Decouple mesh service bind from `MainActivity`

- app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt
This is a navigation anti-pattern and can lead to inconsistencies in the backstack. This also fixes some pretty significant UI jank when adding/connecting to devices.
Some more info on [fixed start destinations](https://developer.android.com/guide/navigation/principles#fixed_start_destination) and [conditional navigation](https://developer.android.com/guide/navigation/use-graph/conditional).
> Don't change nav graph start destination

- app/src/main/java/com/geeksville/mesh/ui/common/components/MaterialBatteryInfo.kt
- app/src/main/java/com/geeksville/mesh/ui/common/icons/Battery.kt
Assets obtained from Material Symbols. Empty battery symbol is used as a foreground, but it wouldn't be too hard to draw it manually given its simplicity. Battery fill level is drawn programmatically based on the node's battery level. Thresholds for color change were pretty arbitrary and based on what I could find online.
No voltage displayed yet, since it's not currently needed.
> Add modern battery info component

- app/src/main/java/com/geeksville/mesh/model/BTScanModel.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/BLEDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/CurrentlyConnectedCard.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/DeviceListItem.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/EmptyStateContent.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/NetworkDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/TitledCard.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/UsbDevices.kt
- app/src/main/res/values/strings.xml
Cleans up the display of the connections screen, while leaving existing functionality intact. I've handled a couple more bluetooth edge cases, including launching the device bluetooth settings screen when disabled.
Pretty large diff, so I'd appreciate some help reviewing that everything still works. I only have a bluetooth radio, so that's all I've really been able to test, but the bulk of these changes are just UI updates. Network and serial device components were pretty straightforward - nothing of note there.
|Bluetooth before|Bluetooth after|
|-|-|
|<video src="https://github.com/user-attachments/assets/ec5b5189-69e6-483c-ae50-33fb8d658a09"/>|<video src="https://github.com/user-attachments/assets/1171efd6-c187-4956-a0e7-f8bf80e62952"/>|
|TCP before|TCP after|
|-|-|
|<img width="300" …
> Clean up Connections UI, fix some friction with Bluetooth

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/service/PacketHandler.kt
Refactors `MeshService` to extract packet queue model data and basic functionality to its own class. A couple of its dependencies cannot be injected yet, so it is just instantiated in service `onCreate`.
Should be a good starting point for all of these packet handlers.
> `MeshService`: extract basic packet handling

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/sharing/ContactSharing.kt
fixes #2804
The `setSharedContactRequested` function was updated to set the `_sharedContactRequested.value` directly instead of launching a coroutine on the `viewModelScope`. This ensures that the value is set on the main thread, which is necessary for UI updates.
Additionally:
-  the AndroidManifest.xml was updated to include a new intent filter for handling shared contact QR codes. 
- trigger qr scan after successful permission grant instead of making user tap scan button again.
> fix(contact-import): streamline shared contact handling 

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/MainAppBar.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
Removes the "About" item from the main menu and displays the app's version name at the bottom of the Connections screen.
The version name is now shown on the left side of the bottom bar, while the scan status text remains on the right side.
> feat(ui): display app version in connections screen

- app/src/main/java/com/geeksville/mesh/android/Logging.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
This commit removes the "Report Bug" button from the connections screen and the associated `reportError` function from the `Logging` class. The functionality to report bugs through a dialog and send reports to a crash reporter service has been removed.
The builtin logging and exception capturing offered by Crashlytics and Datadog are sufficient.
> feat(logging): Remove redundant Report Bug button and related functionality

- .github/workflows/release.yml
- app/build.gradle.kts
- app/src/main/java/com/geeksville/mesh/repository/radio/MockInterface.kt
- buildSrc/src/main/kotlin/Configs.kt
This commit updates the build process to:
- Use the Git tag as the `versionName` for releases.
- Upload build to the appropriate Google Play Store channel based on tag and creates a draft release
- `v1.2.3-internal` goes to `internal test channel`
- `v1.2.3-closed` goes to `closed alpha test channel`
- `v1.2.3-open` goes to `open test channel`
- `v1.2.3` goes to `production channel`
- Use the current epoch seconds as the `versionCode` for development builds if `VERSION_CODE` environment variable is not set.
- Remove `VERSION_NAME_BASE` from `Configs.kt` as it's no longer needed. It is now set from tag during ci, or `Dev Build` as fallback.
- Refactor the GitHub Actions release workflow to be triggered by tags, generate changelogs, and use the tag for versioning and Google Play deployment. …
> ci(release): update release workflow to tag based versioning

- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
This commit updates the `Connections.kt` file to use `collectAsStateWithLifecycle` for observing Flows that drive the UI. This ensures that collection is lifecycle-aware and avoids unnecessary work when the UI is not visible.
Fixes `Region unset` snackbar being erroneously called.
> refactor(connections): use collectAsStateWithLifecycle for UI state

- RELEASE_PROCESS.md
- app/build.gradle.kts
- buildSrc/src/main/kotlin/Configs.kt
This commit significantly revises the `RELEASE_PROCESS.md` to align with the enhanced automation capabilities of the `release.yml` GitHub Action. The process now emphasizes tag-triggered workflows and details the automated steps for building, versioning, changelog generation, draft GitHub Release creation, and draft uploads to Google Play Console tracks.
Key changes include:
-   Revised introduction to highlight tag-based triggers and automated actions.
-   Updated prerequisites to focus on tagging strategy and CI workflow version derivation.
-   Reframing of release phases (Internal/QA, Closed Alpha, Open Alpha/Beta, Production) around the automated workflow, followed by manual finalization steps on GitHub and Google Play Console.
-   Clarified versioning using tag suffixes (e.g., …
> docs!: update release process to reflect automation enhancements

- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
This commit centralizes all repository declarations into the `settings.gradle.kts` file.
The `pluginManagement` and `dependencyResolutionManagement` blocks in `settings.gradle.kts` now define the repositories (google, mavenCentral, gradlePluginPortal, jitpack.io) for the entire project.
Consequently, `buildscript` and `allprojects` repository blocks have been removed from the root `build.gradle.kts`. Individual repository declarations have also been removed from module-level `build.gradle.kts` files (e.g., `app/build.gradle.kts`).
Plugin and library declarations in `gradle/libs.versions.toml` have been updated to remove explicit group and name for plugins, as these are now resolved via the centralized repository configuration and plugin aliases. Version references have been added to …
> build: centralize repository declarations in settings.gradle.kts

- app/src/fdroid/java/com/geeksville/mesh/android/GeeksvilleApplication.kt
- app/src/google/java/com/geeksville/mesh/MeshUtilApplication.kt
- app/src/google/java/com/geeksville/mesh/android/GeeksvilleApplication.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/StreamInterface.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/SwitchPreference.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/components/SettingsItem.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/radio/RadioConfig.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/radio/RadioConfigViewModel.kt
- app/src/main/res/values/strings.xml
This commit refactors the analytics consent mechanism.
The key changes include:
- Moving analytics initialization and consent logic to `GeeksvilleApplication`.
- Introducing `isAnalyticsAvailable` to check for both Datadog and Google Play Services availability.
- Listening to `SharedPreferences` changes to update analytics consent dynamically.
- Removing the analytics toggle from the `Connections` screen.
- Adding an analytics toggle to the `RadioConfig` screen under "Phone Settings".
- Updating the `SettingsItemSwitch` and `SwitchPreference` components to use `ListItem` for better alignment with Material Design guidelines and to add a loading indicator.
- Simplifying the F-Droid `GeeksvilleApplication` by removing unused analytics-related properties.
- Clarifying the analytics consent …
> refactor(analytics): consolidate consent logic, move to Settings

- app/src/google/java/com/geeksville/mesh/ui/map/components/CustomMapLayersSheet.kt
- app/src/main/res/values/strings.xml
closes #2712 
adds a line to show the compatible formats
> 2712  add format types note to custom layers

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/navigation/SettingsRoutes.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/MainAppBar.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/SettingsScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/radio/RadioConfig.kt
- app/src/main/res/values/strings.xml
- Adds dedicated `SettingsScreen`
- Adds Settings as a top-level nav when rendering top app bar (removes contacts/sharing)
- Moves app language setting to `SettingsScreen`
- Moves app theme setting to `SettingsScreen`
Language and theme dialogs could be cleaned up a bit (and not beholden to `UiViewModel`), but I wanted to keep this PR simple.
> More migration to top-level Settings

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/util/HardwareModelExtensions.kt
closes #2918 
added a safe way to get hardware model. 
NOTE - may be needed on other protos at some point 
- UNRECOGNISED has no banner at the top. Maybe should have a placeholder one
> Fix #2918 crash on hw model

- app/src/main/java/com/geeksville/mesh/service/SafeBluetooth.kt
When attempting to reconnect to an out of range or turned off device I sometimes get an exception due to currentWork being scheduled still. This PR fixes that by calling stopCurrentWork to ensure this pending operation is canceled before we attempt to reconnect.
> Fix Bluetooth reconnection logic

- app/src/main/java/com/geeksville/mesh/ui/node/NodeScreen.kt
Adds a Spacer to the bottom of the LazyColumn in NodeScreen to ensure that the FloatingActionButton does not hide the last item in the list.
> fix(ui): Prevent FAB from obscuring NodeScreen content

- app/src/main/java/com/geeksville/mesh/navigation/NavGraph.kt
This causes the app to land on the Nodes screen on launch instead of the Connections screen. Based on discussions in Discord.
> Make Nodes screen the root of the nav graph

- app/build.gradle.kts
This commit updates the `app/build.gradle.kts` file to:
- Set the `google` product flavor as the default.
- Reorder product flavors, moving `google` before `fdroid`.
> fix: Set 'google' as default product flavor

- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
- app/src/main/java/com/geeksville/mesh/ui/node/components/TracerouteButton.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/components/SettingsItem.kt
Aligns the traceroute button with other clickable list items and extracts it to its own file. The button does disable correctly. Disabled alpha not being set is a common issue across all list items currently.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/8079e60c-af6b-4592-8d6a-f4502fc2cf9f"/>|<video src="https://github.com/user-attachments/assets/a2726940-2778-4957-b3a2-6130be0bb6d7"/>|
> Componentize traceroute button

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
The node time was previously set before the configuration was complete. This change moves the time setting operation to after the configuration flow finishes, ensuring the node has the correct time after it's fully configured.
Additionally, the `CONFIG_WAIT_MS` constant was reduced from 250L to 50L.
This one could use some extra hands-on, connection switching testing.
> fix(service): set node time after config completion

- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/MainAppBar.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/Connections.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/SettingsScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/radio/RadioConfig.kt
- app/src/main/res/values/strings.xml
- Renames "Phone Settings" to "App"
- Moves "export range test" to app settings
- Doesn't move "quick chat", since it's already available in the convo screen
- Removes 3-dot top-level menu
- Moves app version to app settings, making it clickable to enable excluded modules
> Move remaining 3-dot menu items to Settings

- app/src/main/java/com/geeksville/mesh/ui/debug/Debug.kt
- app/src/main/res/values/strings.xml
closes #2990 
- Uses the current methods to select a file to export
- same defaults 
- shouldn't get a permission failure.
> move debug export to using URI

- .github/workflows/pr_enforce_labels.yml
closes #2996 
pull latest labels, don't rely on context
> repo: update label check so it doesn't need help

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- app/src/main/java/com/geeksville/mesh/model/RouteDiscovery.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/metrics/TracerouteLog.kt
closes #2896 
- add elapsed time to traceroutes. 
- calculated from packet times, so doesn't need changes to db 
-
> add times to traceroute displays.

- app/src/main/java/com/geeksville/mesh/ui/settings/SettingsScreen.kt
closes #2810 
Update default file name for the config export with:
- add meshtastic
- add nodename 
- add datea
Can't get nodeId from the objects available, so settled for shortname.
> feat #2810 - fix export config file name 

- app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt
When the user enables location tracking on the map, the screen will now stay on. When location tracking is disabled, the screen will behave as normal.
> feat(map): keep screen on when location tracking is enabled

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
Increased the `CONFIG_WAIT_MS` constant from 50L to 250L. This should improve the reliability of configuration changes by allowing more time for the operation to complete.
This reverts a change that introduced some instability.
> fix(service): increase config wait time

- .github/workflows/release.yml
- RELEASE_PROCESS.md
- app/build.gradle.kts
- buildSrc/src/main/kotlin/GitVersionValueSource.kt
Removes the promote-or-upload logic from the release workflow. All Play Store deployments will now directly upload a newly built AAB to the target track. This simplifies the workflow and makes it more predictable.
The `versionCode` is now generated from **epoch minutes** to ensure it is always unique and increasing, preventing conflicts.
The `RELEASE_PROCESS.md` has been updated to reflect these changes, clarifying the new upload-only model and how to iterate on builds.
> fix(release): Simplify Play Store deployment to upload-only

- RELEASE_PROCESS.md
Clarify that merging the release branch back to `main` should be done via a Pull Request to ensure proper review of any hotfixes.
> docs(RELEASE_PROCESS): update release finalization steps

- app/build.gradle.kts
This commit updates the build script to prioritize version code and version name values injected via project properties (`android.injected.version.code` and `android.injected.version.name`).
If these properties are not found, the script falls back to environment variables (`VERSION_CODE` and `VERSION_NAME`), and finally to a git-commit-count-based version code and a default version name (`Configs.VERSION_NAME_BASE`) if neither injected properties nor environment variables are available.
> chore(build): prioritize injected version properties

- fastlane/Fastfile
The assemble_beta task was previously returning the AAB output path directly. This change aligns the task with the Fastlane documentation by assigning the AAB output path to `lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]` without an explicit return. This ensures that the output is available in the lane context for subsequent actions, as expected by Fastlane.
> fix(fastlane): Align assemble_beta task with fastlane documentation

- .github/workflows/pull-request.yml
- .github/workflows/reusable-android-test.yml
This commit introduces the necessary changes to upload Android test results to Codecov.
The `pull-request.yml` workflow is updated to include the `CODECOV_TOKEN` secret.
The `reusable-android-test.yml` workflow is updated to:
- Require the `CODECOV_TOKEN` secret.
- Add a new step to upload test results to Codecov using the `codecov/test-results-action@v1` action. This step runs if the workflow is not cancelled.
> ci: upload Android test results to Codecov

- app/src/main/java/com/geeksville/mesh/service/SafeBluetooth.kt
A large refactor of this class was done in #2551 (v2.6.32) as part of permissions rework. Reverting `SafeBluetooth.kt` to the state prior to the refactor has solved a lot of the issues we're currently facing with bluetooth connection/re-connection.
> revert(safebluetooth): reverts changes to SafeBluetooth.kt

- .github/workflows/release.yml
The paths for the release artifacts (AAB and APKs) have been updated to remove the `./build-artifacts/` prefix.
> ci(release): update artifact paths in release workflow

- app/src/fdroid/java/com/geeksville/mesh/ui/node/NodeMap.kt
- app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt
- app/src/google/java/com/geeksville/mesh/ui/node/NodeMap.kt
- app/src/main/java/com/geeksville/mesh/navigation/ConnectionsNavigation.kt
- app/src/main/java/com/geeksville/mesh/navigation/ContactsNavigation.kt
- app/src/main/java/com/geeksville/mesh/navigation/MapNavigation.kt
- app/src/main/java/com/geeksville/mesh/navigation/NodesNavigation.kt
- app/src/main/java/com/geeksville/mesh/navigation/SettingsNavigation.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/MainAppBar.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/ConnectionsScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/ConnectionsSegmentedBar.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/CurrentlyConnectedInfo.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/UsbDevices.kt
- app/src/main/java/com/geeksville/mesh/ui/contact/Contacts.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeDetail.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/settings/SettingsScreen.kt
Removes global top app bar in favor of local ones for the following screens. A new extension function `NavDestination.hasGlobalAppBar()` was added to `Main.kt` to exclude screens from global top app bar usage to support incremental migration. There are no visual changes. This should unblock https://github.com/meshtastic/Meshtastic-Android/pull/3010.
- `ConnectionsRoutes.Connections`
- `ContactsRoutes.Contacts`
- `MapRoutes.Map`
- `NodeDetailRoutes.NodeMap`
- `NodesRoutes.Nodes`
- `NodesRoutes.NodeDetail`
- `SettingsRoutes.Settings`
[Screen_recording_20250917_164852.webm](https://github.com/user-attachments/assets/27400e6b-a545-4a11-a04f-38eb55f92a20)
> Start migration away from global top app bar

- app/src/fdroid/java/com/geeksville/mesh/ui/map/MapView.kt
The MapViewModel is now retrieved using `hiltViewModel()` instead of `viewModel()`.
> refactor(map): use hiltViewModel for MapViewModel

- app/src/fdroid/java/com/geeksville/mesh/ui/map/MapViewModel.kt
- app/src/google/java/com/geeksville/mesh/ui/map/MapViewModel.kt
- app/src/main/java/com/geeksville/mesh/navigation/MapNavigation.kt
- app/src/main/java/com/geeksville/mesh/ui/map/BaseMapViewModel.kt
- app/src/main/java/com/geeksville/mesh/ui/map/MapScreen.kt
With `MapView` now wrapped in a `Scaffold`, it makes sense to wrap the whole thing in `MapScreen` to keep the nav logic simple, enable easy previews, etc. This should also make decoupling from `UiViewModel` a bit easier.
> Add `MapScreen`

- .github/workflows/release.yml
- fastlane/Fastfile
This commit refactors the GitHub Actions workflow for releases and updates the Fastlane configuration to improve the release process.
The GitHub Actions workflow (`release.yml`) has been modified to:
- Only run Gradle setup, AAB/APK uploads, and F-Droid release jobs for internal builds (tags containing '-internal').
- Consolidate artifact downloading in the `manage-github-release` job.
- Create draft releases for internal builds.
- Update existing internal releases to final release names (e.g., closed, open, production) when corresponding tags are pushed, and mark them as non-draft and pre-release accordingly.
- Remove the separate changelog generation step for pre-releases, relying on GitHub's auto-generated release notes.
The Fastlane configuration (`Fastfile`) has been updated to:
- …
> ci: streamline release process and artifact handling

- app/src/main/java/com/geeksville/mesh/database/NodeRepository.kt
- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- core/database/src/main/kotlin/org/meshtastic/core/database/dao/NodeInfoDao.kt
- core/prefs/src/main/kotlin/org/meshtastic/core/prefs/mesh/MeshPrefs.kt
Replaces separate calls for installing MyNodeInfo and the node database with a single transactional `installConfig` operation in the DAO. This ensures atomicity when updating the local node configuration from the device.
Refactors the `MeshService` to use this new transactional method and removes the now-redundant individual installation functions from `NodeRepository`.
Additionally, this commit simplifies the device address handling logic in `MeshService` by removing the local `StateFlow` and relying directly on `MeshPrefs`.
> feat(db): introduce transactional config installation

- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/common/components/MainAppBar.kt
Also cleans up some of the logic surrounding top-level screens, as they all employ their own instance of `MainAppBar`.
> Decouple `MainAppBar` from `UiViewModel`

- .github/workflows/release.yml
- RELEASE_PROCESS.md
This introduces several improvements to the release workflow:
- **Build Provenance:** Adds SLSA Level 3 provenance attestation for Google Play and F-Droid build artifacts using `actions/attest-build-provenance`. This enhances security by providing verifiable information about how the builds were produced.
- **Refined Release Naming:** The GitHub release name now directly uses `github.ref_name` for internal releases. The tag name for releases is now prefixed with `v` (e.g., `v1.2.3`).
- **Dynamic Artifact Paths:** The `create-internal-release` job now dynamically determines the paths of available build artifacts (AAB, Google APK, F-Droid APK) to include in the GitHub release, rather than assuming all will be present.
- **Simplified JDK Setup:** Removed redundant blank lines in the JDK …
> ci(release): add build provenance and streamline release process

- app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt
- app/src/google/java/com/geeksville/mesh/ui/map/components/MapFilterDropdown.kt
- app/src/main/java/com/geeksville/mesh/ui/map/BaseMapViewModel.kt
- core/prefs/src/main/kotlin/org/meshtastic/core/prefs/map/MapPrefs.kt
- core/strings/src/main/res/values/strings.xml
This commit introduces a "last heard" filter to the map, allowing users to filter nodes based on when they were last heard from.
The filter options include "Any", "1 Hour", "8 Hours", "24 Hours", and "48 Hours".
This change includes:
- Adding a `lastHeardFilter` preference to `MapPrefs`.
- Updating the `MapFilterDropdown` to include options for the last heard filter.
- Modifying `BaseMapViewModel` to handle the new filter state and logic.
- Updating `MapView` to apply the last heard filter to displayed nodes.
- Adding new string resources for the filter options.
> feat(map): add last heard filter for map nodes

- app/src/google/java/com/geeksville/mesh/ui/map/MapView.kt
- app/src/google/java/com/geeksville/mesh/ui/map/components/MapControlsOverlay.kt
- app/src/google/java/com/geeksville/mesh/ui/map/components/MapFilterDropdown.kt
- app/src/google/java/com/geeksville/mesh/ui/node/NodeMap.kt
- app/src/main/java/com/geeksville/mesh/ui/map/BaseMapViewModel.kt
- core/prefs/src/main/kotlin/org/meshtastic/core/prefs/map/MapPrefs.kt
As a follow-on from #3219 This introduces a "last heard" filter specifically for node tracks on the map. This allows users to filter the displayed track points based on how recently they were recorded.
- Added `lastHeardTrackFilter` to `MapPrefs` to store the filter setting.
- Implemented `NodeMapFilterDropdown` to provide a UI for selecting the filter duration.
- Updated `MapControlsOverlay` to display the new filter dropdown when viewing a node's track.
- Modified `MapView` to filter and display node track points based on the selected `lastHeardTrackFilter`. Polyline segments and markers are now alpha blended based on their age.
- Updated `BaseMapViewModel` to include `lastHeardTrackFilter` in `MapFilterState`.
- Renamed `nodeTrack` to `nodeTracks` in …
> feat(map): Add last heard filter for node tracks

- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/metrics/TracerouteLog.kt
- core/ui/src/main/kotlin/org/meshtastic/core/ui/component/LoraSignalIndicator.kt
Add colour coding to the dbm numbers on traceroutes.
Currently bold, but I'm unsure about that - but the green is a bit too light on lightmode
> add colour coding to traceroutes

- app/src/main/java/com/geeksville/mesh/ui/node/NodesViewModel.kt
- core/datastore/src/main/kotlin/org/meshtastic/core/datastore/UiPreferencesDataSource.kt
- core/datastore/src/main/kotlin/org/meshtastic/core/datastore/di/DataStoreModule.kt
- core/prefs/src/main/kotlin/org/meshtastic/core/prefs/ui/UiPrefs.kt
We're already manually converting these to `Flow`. DataStore gives us `Flow` by default.
> Migrate node sort prefs to datastore

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- For Android Q and above, use `FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE` and `FOREGROUND_SERVICE_TYPE_LOCATION` if location permission is granted.
- If location permission is not granted on Android Q and above, use only `FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE`.
- For versions below Android Q, no specific foreground service type is set.
- Catch generic `Exception` during `startForeground` and log it using Timber, replacing more specific `SecurityException` handling.
> fix(service): Update foreground service type and error handling

- app/src/google/java/com/geeksville/mesh/ui/map/components/NodeClusterMarkers.kt
This commit updates the map clustering behavior by setting the minimum number of items required to form a cluster to 10.
> feat(map): set minimum cluster size to 10

- app/build.gradle.kts
- gradle.properties
This commit introduces specific configurations for the F-Droid build variant:
- Increases `MaxMetaspaceSize` from 1g to 2g in `gradle.properties`.
- Disables `isMinifyEnabled` and `isShrinkResources` for the `fdroid` product flavor in `app/build.gradle.kts`.
- Adds logic to `app/build.gradle.kts` to disable Gradle tasks containing keywords like "crashlytics", "google", or "datadog" when building for the F-Droid variant.
> chore(fdroid): Configure F-Droid build variant

- app/src/main/java/com/geeksville/mesh/service/MeshService.kt
- app/src/main/java/com/geeksville/mesh/ui/message/MessageViewModel.kt
- core/database/schemas/org.meshtastic.core.database.MeshtasticDatabase/21.json
- core/database/src/main/kotlin/org/meshtastic/core/database/MeshtasticDatabase.kt
- core/database/src/main/kotlin/org/meshtastic/core/database/entity/NodeEntity.kt
- core/database/src/main/kotlin/org/meshtastic/core/database/model/Node.kt
- core/service/src/main/kotlin/org/meshtastic/core/service/ServiceAction.kt
- feature/node/src/main/kotlin/org/meshtastic/feature/node/list/NodeListViewModel.kt
This introduces the ability to import and send manually verified shared contacts.
resolves #3281 
When importing a shared contact, it is now marked as `manuallyVerified`. The `AddSharedContact` service action has been renamed to `ImportContact` to better reflect this. A new `SendContact` service action has been added to send shared contacts to the radio.
The `NodeEntity` and `Node` models have been updated to include a `manuallyVerified` boolean field, which defaults to false and is only set to true when a contact is scanned or imported manually.
When sending a direct message, if the firmware version is 2.7.12 or newer, the destination contact will be sent as a shared contact instead of favoriting the node. This change aims to improve contact management, especially for devices with newer …
> feat(contact): add manually verified shared contact support

- app/src/main/java/com/geeksville/mesh/ui/connections/ConnectionsScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/connections/components/BLEDevices.kt
- core/strings/src/main/res/values/strings.xml
Previously, results of a bluetooth scan were listed in a dialog without filtering out paired devices. This is a bit noisy, especially when the device list in the dialog matches the already displayed "Paired devices" section.
This PR removes the dialog in favor of a "Available devices" section on `ConnectionsScreen`. This section displays the same list of scanned bluetooth devices, but with the bonded devices filtered out.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/c70eb477-1cf6-49dd-aced-a687fd119904"/>|<video src="https://github.com/user-attachments/assets/38c17826-f29e-4460-87f6-6e1e6d09011a"/>|
> `ConnectionsScreen` available BLE devices

- app/detekt-baseline.xml
- app/src/main/java/com/geeksville/mesh/MainActivity.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/node/NodeListScreen.kt
- app/src/main/java/com/geeksville/mesh/ui/sharing/ContactSharing.kt
- app/src/main/java/com/geeksville/mesh/ui/sharing/SharedContactDialog.kt
- app/src/main/java/com/geeksville/mesh/ui/sharing/SharedContactViewModel.kt
- core/strings/src/main/res/values/strings.xml
- feature/node/detekt-baseline.xml
- feature/node/src/main/kotlin/org/meshtastic/feature/node/list/NodeListViewModel.kt
This looks like it has been broken for a while. Previously, deep link for a scanned contact QR code was silently swallowed. The deep link is handled, but the confirmation dialog was not shown. This PR adds handling to `MainScreen` to actually show the expected dialog (similar to scanned channel QR code). Since this dialog is shared with `NodeListScreen`, I extracted its logic to `SharedContactDialog` and `SharedContactViewModel`.
> Fix shared contact deeplink

- .github/workflows/create-internal-release.yml
- .github/workflows/promote-release.yml
Configures the git user and email for the `create-internal-release` and `promote-release` workflows before creating and pushing tags. This ensures that the `github-actions[bot]` is correctly attributed as the author of the tags.
> ci(workflows): configure git user for release workflows

- .github/workflows/create-internal-release.yml
- .github/workflows/promote-release.yml
- .github/workflows/release.yml
The `Release` environment, which may contain secrets or require specific protection rules, was incorrectly applied to the `create-internal-release` and `promote-release` workflows. It is now correctly applied only to the `release` workflow's `prepare-build-info` job, which requires access to this environment.
The environment has been removed from the `create-internal-tag` job in the `create-internal-release.yml` workflow and the `promote` job in the `promote-release.yml` workflow.
> ci(github-actions): move release environment to correct workflow

- .github/workflows/release.yml
Adds a new `check-versioncode-google-play` job to the release workflow. This job uses Fastlane to verify if the current `versionCode` already exists on the Google Play internal track before proceeding with a build and deploy.
The `release-google` and `release-fdroid` jobs are now conditional on this check:
- If the `versionCode` does not exist, the internal build and upload to Google Play and F-Droid proceeds as normal.
- If the `versionCode` already exists on an internal release, the build and upload steps are skipped to prevent failures, but promotion logic can still run.
- When promoting to beta or production, the workflow now fails if the `versionCode` is not found on the internal track, preventing promotion errors.
> ci(release): check for existing versionCode on Google Play before build

- .github/workflows/promote.yml
- .github/workflows/release.yml
The GitHub release name for both draft releases and promotions will now include the application version code in parentheses, following the tag name.
This provides more immediate context about the specific build directly in the release title. The `promote-play-release` action version is also updated.
> ci(release): include version code in GitHub release name

- .github/workflows/post-release-cleanup.yml
This commit introduces a new GitHub Actions workflow for cleaning up pre-release tags and draft releases after a final release has been published.
The workflow is manually triggered via `workflow_dispatch` and requires a `base_version` to identify the artifacts to be removed. To prevent accidental deletion, it includes a `confirm_deletion` boolean input which defaults to a dry run.
The workflow consists of two jobs:
- `cleanup_tags`: Deletes all Git tags matching the pattern `v<base_version>-*`.
- `cleanup_releases`: Deletes all draft releases that have the `base_version` in their name.
> feat(ci): add post-release cleanup workflow

- app/detekt-baseline.xml
- app/src/main/java/com/geeksville/mesh/MeshUtilApplication.kt
- app/src/main/java/com/geeksville/mesh/model/UIState.kt
- app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
- app/src/main/java/com/geeksville/mesh/ui/Main.kt
- app/src/main/java/com/geeksville/mesh/ui/sharing/Channel.kt
- app/src/main/java/com/geeksville/mesh/ui/sharing/ChannelViewModel.kt
DI for this is already set up to correctly instantiate `PlatformAnalytics` as a singleton. There shouldn't be a need to hold a reference for static access in `MeshUtilApplication`. This also decouples any direct dependencies on `MeshUtilApplication`.
> Inject `PlatformAnalytics` directly

- core/ui/src/main/kotlin/org/meshtastic/core/ui/component/LoraSignalIndicator.kt
- core/ui/src/main/kotlin/org/meshtastic/core/ui/component/MaterialBatteryInfo.kt
- core/ui/src/main/kotlin/org/meshtastic/core/ui/component/SignalInfo.kt
- feature/node/src/main/kotlin/org/meshtastic/feature/node/component/DistanceInfo.kt
- feature/node/src/main/kotlin/org/meshtastic/feature/node/component/ElevationInfo.kt
- feature/node/src/main/kotlin/org/meshtastic/feature/node/component/IconInfo.kt
- feature/node/src/main/kotlin/org/meshtastic/feature/node/component/LastHeardInfo.kt
- feature/node/src/main/kotlin/org/meshtastic/feature/node/component/NodeItem.kt
- feature/node/src/main/kotlin/org/meshtastic/feature/node/component/SatelliteCountInfo.kt
This commit introduces a `contentColor` parameter to various info-related composable functions to allow for more flexible color theming.
The following components have been updated to accept and utilize the new `contentColor` parameter:
- `IconInfo`
- `MaterialBatteryInfo`
- `SignalInfo`
- `LoraSignalIndicator`
- `DistanceInfo`
- `ElevationInfo`
- `LastHeardInfo`
- `SatelliteCountInfo`
The `NodeItem` composable has also been updated to pass the appropriate `contentColor` to these components, ensuring a consistent look and feel.
> feat: Add contentColor parameter to info components

- .github/workflows/promote.yml
- .github/workflows/release.yml
The `base_version` input is incorrect for the `softprops/action-gh-release` action. This commit updates the `release.yml` and `promote.yml` workflows to use the correct `tag_name` input for specifying the release tag.
> ci: Use `tag_name` input in release and promote workflows

- app/build.gradle.kts
Fixes startup crash in the Google app flavor. Re-adds the Google Services and Crashlytics plugins that were removed in https://github.com/meshtastic/Meshtastic-Android/pull/3365.
> Fix google build

- app/src/main/java/com/geeksville/mesh/model/MetricsViewModel.kt
- core/strings/src/main/res/values/strings.xml
Removes the string formatting argument from the `fallback_node_name` string resource. The node's unique ID is now appended directly in the code, providing more flexibility in formatting.
addresses: https://console.firebase.google.com/u/0/project/meshutil/crashlytics/app/android:com.geeksville.mesh/issues/51118c6f75d470f9794c5bd2c7c092e7
> fix: Change fallback node name format

- .github/workflows/post-release-cleanup.yml
This commit updates the `post-release-cleanup.yml` workflow to prevent errors when a release has a null `tagName`.
The `jq` command is modified to add a `tagName != null` check before attempting to match the tag prefix. This ensures the workflow runs successfully even if some releases lack a tag name.
> ci(github-actions): Check for null tagName in post-release-cleanup

- feature/node/src/main/kotlin/org/meshtastic/feature/node/component/PositionSection.kt
Removes the condition that hides the "Exchange Position" action, making it always visible regardless of whether the node is messageable.
> feat(node): Always show exchange position action
